/**
 * Additional questions for existing sets (merged by slug at seed time).
 *
 * Purpose: expand each set progressively toward a ≥50-question bank without
 * rewriting the base sets-*.mjs files. The seed runner merges:
 *
 *    mergedQuestions = [...baseSet.questions, ...(EXTRA[slug] ?? [])]
 *
 * Guidelines:
 *   - Keep question shape identical to base sets.
 *   - Original content only, written against PUBLIC exam blueprints.
 *   - Cover topics not yet covered in the base file (avoid duplicates).
 */

// ════════════════════════════════════════════════════════════════════
// AWS Solutions Architect Associate — 35 extras → 50 total
// ════════════════════════════════════════════════════════════════════
const AWS_SAA_EXTRAS = [
  {
    type: 'multiple',
    question: '¿Qué servicio entrega contenido estático con baja latencia global mediante una red de edge locations?',
    options: { A: 'Amazon CloudFront', B: 'Amazon S3', C: 'Elastic Load Balancer', D: 'AWS Global Accelerator' },
    answer: ['A'],
    explanation: 'CloudFront es un CDN que cachea contenido en cientos de edge locations. Global Accelerator enruta TCP/UDP a regiones, no cachea.',
    domain: 'Networking',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué servicio permite gestionar secretos con rotación automática nativa para RDS?',
    options: { A: 'AWS Systems Manager Parameter Store', B: 'AWS Secrets Manager', C: 'AWS KMS', D: 'AWS IAM' },
    answer: ['B'],
    explanation: 'Secrets Manager ofrece rotación automática con Lambda integrada para RDS, Redshift, DocumentDB.',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Tu aplicación necesita enviar notificaciones push a móviles, email y SQS desde un solo evento. ¿Qué servicio usas?',
    options: { A: 'SQS', B: 'SNS', C: 'EventBridge', D: 'Kinesis' },
    answer: ['B'],
    explanation: 'SNS es pub/sub con fan-out a múltiples subscribers: SQS, Lambda, email, SMS, HTTP, mobile push.',
    domain: 'Integración',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué tipo de EBS Volume ofrece mayor IOPS por GB para workloads críticos de BD?',
    options: { A: 'gp3', B: 'io2 Block Express', C: 'st1', D: 'sc1' },
    answer: ['B'],
    explanation: 'io2 Block Express alcanza hasta 256.000 IOPS y 4.000 MB/s. gp3 es default balanceado. st1/sc1 son HDD.',
    domain: 'Almacenamiento',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Una app requiere consistencia fuerte, baja latencia <10ms y escala automática. ¿Qué BD NoSQL usar?',
    options: { A: 'DynamoDB con Strongly Consistent Reads', B: 'RDS Multi-AZ', C: 'Redshift', D: 'Neptune' },
    answer: ['A'],
    explanation: 'DynamoDB ofrece single-digit ms latency, escala automática y lecturas fuertemente consistentes si se solicitan.',
    domain: 'Bases de Datos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué servicio gestionado permite hacer ETL serverless con interfaz visual?',
    options: { A: 'AWS Glue', B: 'EMR', C: 'Data Pipeline', D: 'AppFlow' },
    answer: ['A'],
    explanation: 'Glue es ETL serverless con crawlers, Data Catalog, Glue Studio (visual) y Glue Jobs (Spark/Python).',
    domain: 'Analytics',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Para ejecutar código en respuesta a eventos de S3, ¿qué configuración usar?',
    options: {
      A: 'Polling desde EC2',
      B: 'S3 Event Notifications → Lambda',
      C: 'CloudWatch Metrics',
      D: 'SQS consumiendo S3',
    },
    answer: ['B'],
    explanation: 'S3 Event Notifications pueden disparar Lambda, SNS o SQS. Es event-driven nativo.',
    domain: 'Serverless',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Una VPC privada debe acceder a S3 sin salir a internet. ¿Qué componente usar?',
    options: { A: 'NAT Gateway', B: 'Internet Gateway', C: 'VPC Gateway Endpoint', D: 'Transit Gateway' },
    answer: ['C'],
    explanation: 'Gateway Endpoints (S3, DynamoDB) son gratuitos y mantienen el tráfico dentro de la red AWS.',
    domain: 'Networking',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Cuál es la diferencia clave entre Security Groups y NACLs?',
    options: {
      A: 'Son idénticos',
      B: 'SG es stateful y a nivel de ENI; NACL es stateless y a nivel de subnet',
      C: 'SG a nivel subnet; NACL a nivel ENI',
      D: 'Solo SG soporta reglas de denegación',
    },
    answer: ['B'],
    explanation: 'SG: stateful, solo allow rules, actúa en ENIs. NACL: stateless, allow+deny, actúa en subnets.',
    domain: 'Networking',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Para proteger una aplicación web contra SQL injection y XSS en edge, ¿qué servicio usar?',
    options: { A: 'AWS Shield Standard', B: 'AWS WAF', C: 'Security Hub', D: 'GuardDuty' },
    answer: ['B'],
    explanation: 'WAF filtra L7 con managed rules (AWS Managed Rules) o custom rules. Shield es DDoS. GuardDuty detecta amenazas.',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Una flotilla de EC2 escala en función de la longitud de una cola SQS. ¿Qué política de Auto Scaling usar?',
    options: {
      A: 'Simple scaling policy',
      B: 'Target Tracking scaling policy con métrica custom (BacklogPerInstance)',
      C: 'Scheduled scaling',
      D: 'Manual scaling',
    },
    answer: ['B'],
    explanation: 'Target Tracking con BacklogPerInstance (ApproximateNumberOfMessages/N_instances) es el patrón recomendado.',
    domain: 'Escalabilidad',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué servicio centraliza políticas y configuración multi-cuenta?',
    options: { A: 'AWS Organizations + SCPs', B: 'IAM users', C: 'Cognito', D: 'Directory Service' },
    answer: ['A'],
    explanation: 'Organizations con Service Control Policies (SCPs) aplica límites preventivos a cuentas hijas.',
    domain: 'Governance',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Para cumplir con residencia de datos en UE, ¿qué hacer?',
    options: {
      A: 'Usar únicamente regiones europeas (ej. eu-west-1)',
      B: 'Activar encriptación',
      C: 'Replicar a us-east-1',
      D: 'Activar CloudTrail',
    },
    answer: ['A'],
    explanation: 'La residencia se controla eligiendo regiones donde se almacenan y procesan los datos.',
    domain: 'Compliance',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Una Lambda necesita acceder a una RDS en una VPC privada. ¿Cómo configurarla?',
    options: {
      A: 'Lambda no puede acceder a VPC privadas',
      B: 'Configurar la Lambda con VPC config apuntando a subnets y security groups',
      C: 'Pasar por Internet Gateway',
      D: 'Usar un bucket S3 como proxy',
    },
    answer: ['B'],
    explanation: 'Lambda soporta VPC config; se inyecta una ENI elástica en subnets especificadas.',
    domain: 'Serverless',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Seleccione DOS beneficios de usar Savings Plans sobre On-Demand.',
    options: {
      A: 'Descuento hasta 72% por compromiso de 1 o 3 años',
      B: 'Flexibilidad para mover workloads entre familias (Compute Savings Plans)',
      C: 'Gratis',
      D: 'Cero compromiso financiero',
    },
    answer: ['A', 'B'],
    explanation: 'Savings Plans: descuento a cambio de compromiso de $/hr. Compute SP aplica a EC2/Fargate/Lambda de cualquier familia/región.',
    domain: 'Optimización de Costos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué hace VPC Peering?',
    options: {
      A: 'Conecta dos VPCs permitiendo comunicación privada entre ellas',
      B: 'Conecta VPC a internet',
      C: 'Conecta VPC a on-premises',
      D: 'Balancea tráfico',
    },
    answer: ['A'],
    explanation: 'Peering conecta 2 VPCs sin tránsito transitivo (A-B, B-C no implica A-C). Transit Gateway sí permite tránsito.',
    domain: 'Networking',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Para centralizar routing de decenas de VPCs y redes on-prem, ¿qué usar?',
    options: { A: 'VPC Peering', B: 'Transit Gateway', C: 'Direct Connect solo', D: 'Client VPN' },
    answer: ['B'],
    explanation: 'TGW es un hub cloud WAN: soporta miles de VPCs + VPN + DX + SD-WAN.',
    domain: 'Networking',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un ALB necesita enrutar /api a un target group y /web a otro. ¿Qué feature usar?',
    options: {
      A: 'Listener rules con path-based routing',
      B: 'Target group weights',
      C: 'Network ACLs',
      D: 'Route 53',
    },
    answer: ['A'],
    explanation: 'ALB soporta path-based, host-based y header-based routing en sus listener rules.',
    domain: 'Networking',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué tipo de Load Balancer opera en L4 con soporte de IP estática y UDP?',
    options: { A: 'ALB', B: 'NLB', C: 'Classic LB', D: 'Gateway LB' },
    answer: ['B'],
    explanation: 'NLB: L4 TCP/UDP/TLS con IPs estáticas por AZ y millones de requests/sec.',
    domain: 'Networking',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'CloudWatch Logs de una app deben enviarse a un bucket S3 para análisis con Athena. ¿Cómo?',
    options: {
      A: 'Export tasks de CloudWatch Logs → S3 o Subscription filter → Kinesis Firehose → S3',
      B: 'Copia manual diaria',
      C: 'No es posible',
      D: 'Usar CloudTrail',
    },
    answer: ['A'],
    explanation: 'Export tasks son batch. Subscription filter a Kinesis Firehose permite near real-time streaming a S3.',
    domain: 'Observabilidad',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué patrón de integración con Lambda conviene para procesar streams masivos de eventos en orden?',
    options: {
      A: 'SQS Standard',
      B: 'Kinesis Data Streams (con shards)',
      C: 'SNS',
      D: 'Step Functions',
    },
    answer: ['B'],
    explanation: 'Kinesis mantiene orden por partition key y escala con shards. SQS Standard no garantiza orden global.',
    domain: 'Integración',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Una aplicación debe estar disponible aun si toda una región AWS cae. ¿Qué arquitectura?',
    options: {
      A: 'Multi-AZ en una sola región',
      B: 'Multi-Region con replicación y Route 53 failover',
      C: 'Single AZ con backups',
      D: 'EC2 con snapshots',
    },
    answer: ['B'],
    explanation: 'Multi-Region: réplicas en 2+ regiones con health checks de Route 53 para failover activo o pasivo.',
    domain: 'Alta Disponibilidad',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué herramienta permite provisionar infraestructura AWS con YAML o JSON declarativo?',
    options: { A: 'AWS CloudFormation', B: 'AWS Config', C: 'AWS CLI scripts', D: 'AWS SDK' },
    answer: ['A'],
    explanation: 'CloudFormation es IaC nativo de AWS con stacks, change sets y StackSets multi-cuenta.',
    domain: 'IaC',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué ofrece AWS CDK sobre CloudFormation puro?',
    options: {
      A: 'Solo JSON',
      B: 'IaC con lenguajes de programación (TypeScript, Python, Java) que compilan a CloudFormation',
      C: 'Solo infraestructura gráfica',
      D: 'Reemplaza totalmente a CFN',
    },
    answer: ['B'],
    explanation: 'CDK da abstracciones de alto nivel (constructs) y sintetiza templates CFN.',
    domain: 'IaC',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Una empresa requiere que admins usen hardware MFA (YubiKey). ¿Dónde se configura?',
    options: {
      A: 'IAM → Users → Security credentials → Assigned MFA device',
      B: 'Cognito',
      C: 'SSO solamente',
      D: 'No soportado',
    },
    answer: ['A'],
    explanation: 'IAM soporta virtual MFA (TOTP), hardware MFA (U2F/FIDO) y SMS (deprecating).',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué servicio inspecciona acciones inusuales en logs de API y detecta amenazas ML-based?',
    options: { A: 'Amazon GuardDuty', B: 'AWS Inspector', C: 'AWS Config', D: 'CloudTrail' },
    answer: ['A'],
    explanation: 'GuardDuty analiza CloudTrail, VPC Flow Logs y DNS logs con ML para detectar threats.',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué proporciona AWS Inspector?',
    options: {
      A: 'Escaneo automatizado de vulnerabilidades en EC2, ECR y Lambda',
      B: 'Análisis de logs',
      C: 'Backup',
      D: 'Gestión de secretos',
    },
    answer: ['A'],
    explanation: 'Inspector v2 escana CVEs en EC2, imágenes de ECR y funciones Lambda continuamente.',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Cola FIFO de SQS vs Standard: ¿qué garantiza FIFO?',
    options: {
      A: 'Menor latencia',
      B: 'Orden exacto y exactly-once processing (con throughput menor ~300 msg/s sin batching)',
      C: 'Mejor precio',
      D: 'Mayor throughput',
    },
    answer: ['B'],
    explanation: 'FIFO: orden garantizado y exactly-once. Standard: at-least-once, best-effort ordering, throughput ilimitado.',
    domain: 'Integración',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Un cliente requiere cifrado de datos en tránsito entre EC2 y RDS. ¿Qué hacer?',
    options: {
      A: 'Activar SSL/TLS en el engine de RDS y conectar con cert',
      B: 'No es posible',
      C: 'Solo con VPN',
      D: 'Usar IPSec',
    },
    answer: ['A'],
    explanation: 'RDS soporta TLS con el bundle de certificados AWS (rds-combined-ca-bundle).',
    domain: 'Seguridad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué servicio permite búsqueda full-text gestionada sobre documentos JSON?',
    options: { A: 'Amazon OpenSearch Service', B: 'DynamoDB', C: 'Athena', D: 'Kinesis' },
    answer: ['A'],
    explanation: 'OpenSearch (fork de Elasticsearch) para búsqueda, analítica y observabilidad.',
    domain: 'Analytics',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Para reducir latencia de lectura de DynamoDB a microsegundos, ¿qué capa añadir?',
    options: { A: 'ElastiCache manual', B: 'DynamoDB Accelerator (DAX)', C: 'CloudFront', D: 'Aurora Replicas' },
    answer: ['B'],
    explanation: 'DAX es un cache in-memory write-through específico para DynamoDB.',
    domain: 'Performance',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un patrón de API pública serverless HTTP con auth. ¿Qué combinación usar?',
    options: {
      A: 'API Gateway (HTTP o REST) + Lambda + Cognito / IAM authorizer',
      B: 'EC2 expuesto',
      C: 'S3 estático solo',
      D: 'RDS público',
    },
    answer: ['A'],
    explanation: 'API Gateway + Lambda con authorizers Cognito/JWT/Lambda es el patrón serverless standard.',
    domain: 'Serverless',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué feature de Aurora permite reads a nivel mundial con <1s de lag?',
    options: {
      A: 'Aurora Global Database',
      B: 'Multi-AZ',
      C: 'Read Replicas en una región',
      D: 'Aurora Serverless',
    },
    answer: ['A'],
    explanation: 'Aurora Global Database replica a otras regiones con lag sub-segundo mediante storage-level replication.',
    domain: 'Bases de Datos',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Aurora Serverless v2 es adecuado para:',
    options: {
      A: 'Workloads con picos variables e impredecibles donde se quiere escala instant',
      B: 'Cargas constantes al 100% CPU',
      C: 'BD offline',
      D: 'Almacenamiento de objetos',
    },
    answer: ['A'],
    explanation: 'Serverless v2 escala ACUs en segundos sin downtime, ideal para workloads con picos.',
    domain: 'Bases de Datos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Seleccione DOS patrones válidos para caching en AWS.',
    options: {
      A: 'ElastiCache Redis para session store',
      B: 'CloudFront para contenido estático/API',
      C: 'DynamoDB como cache primario',
      D: 'EC2 como cache dedicado manual',
    },
    answer: ['A', 'B'],
    explanation: 'Patrones recomendados: ElastiCache (Redis/Memcached) para app cache, CloudFront para edge cache.',
    domain: 'Performance',
    difficulty: 'medium',
  },
];

// ════════════════════════════════════════════════════════════════════
// Scrum Master PSM I — 35 extras → 50 total
// ════════════════════════════════════════════════════════════════════
const SCRUM_PSM_EXTRAS = [
  {
    type: 'multiple',
    question: '¿Quién se encarga del ordenamiento (priorización) del Product Backlog?',
    options: { A: 'Scrum Master', B: 'Product Owner', C: 'Stakeholders', D: 'Developers' },
    answer: ['B'],
    explanation: 'El PO es accountable del contenido y orden del Product Backlog.',
    domain: 'Roles',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Un Scrum Team ideal tiene:',
    options: { A: '≤10 personas en total', B: '20 personas', C: 'Solo 3', D: 'Sin límite' },
    answer: ['A'],
    explanation: 'La Guide 2020 recomienda equipos pequeños (típicamente 10 o menos). Equipos grandes se reorganizan en múltiples Scrum Teams.',
    domain: 'Equipo Scrum',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Durante la Sprint Planning se aborda:',
    options: {
      A: '¿Por qué es valioso este Sprint? ¿Qué puede hacerse? ¿Cómo se hará?',
      B: 'Solo estimación',
      C: 'Solo el what',
      D: 'Presentación al cliente',
    },
    answer: ['A'],
    explanation: 'La Guide 2020 estructura Sprint Planning en tres topics: Why (Sprint Goal), What (selección), How (plan).',
    domain: 'Eventos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El Sprint Goal:',
    options: {
      A: 'Cambia cada día',
      B: 'Es fijo durante el Sprint, pero el alcance puede renegociarse',
      C: 'No existe',
      D: 'Lo define el stakeholder',
    },
    answer: ['B'],
    explanation: 'El Sprint Goal es el commitment del Sprint. El alcance puede ajustarse siempre que sirva al Sprint Goal.',
    domain: 'Sprint',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Quién es responsable de la calidad del Increment?',
    options: { A: 'Scrum Master', B: 'Product Owner', C: 'Developers', D: 'Stakeholders' },
    answer: ['C'],
    explanation: 'Los Developers son accountable de crear un Increment útil y valioso cada Sprint, cumpliendo la DoD.',
    domain: 'Roles',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'La Sprint Retrospective busca:',
    options: {
      A: 'Inspeccionar el producto',
      B: 'Inspeccionar al equipo, interacciones, procesos, herramientas y DoD — y planear mejoras',
      C: 'Estimar historias',
      D: 'Demo al cliente',
    },
    answer: ['B'],
    explanation: 'Retrospective: foco en personas, procesos, relaciones, herramientas, DoD — y acciones concretas de mejora.',
    domain: 'Eventos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Una nueva Retrospective comienza cuando:',
    options: {
      A: 'Termina la Sprint Review',
      B: 'Termina Sprint Planning',
      C: 'Inicia el Sprint',
      D: 'Finaliza la Daily',
    },
    answer: ['A'],
    explanation: 'Orden: Sprint Planning → Dailies → Sprint Review → Sprint Retrospective → (siguiente) Sprint Planning.',
    domain: 'Eventos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Durante el Sprint, el Product Backlog:',
    options: {
      A: 'Está congelado',
      B: 'Puede refinarse y actualizarse continuamente',
      C: 'Solo lo toca el SM',
      D: 'Lo aprueba el cliente diariamente',
    },
    answer: ['B'],
    explanation: 'El Product Backlog es emergente. Refinement es una actividad ongoing, no un evento formal.',
    domain: 'Artefactos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un PBI "Ready" implica:',
    options: {
      A: 'Es suficientemente claro, estimado y pequeño para entrar a un Sprint',
      B: 'Está entregado',
      C: 'Es crítico',
      D: 'Tiene prioridad alta',
    },
    answer: ['A'],
    explanation: 'Definition of Ready (práctica común, no mandataria) garantiza que los PBIs están preparados para Sprint Planning.',
    domain: 'Refinement',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS escenarios donde el Scrum Master debe ayudar a la organización.',
    options: {
      A: 'Planeando e implementando adopción de Scrum',
      B: 'Removiendo barreras entre stakeholders y equipos',
      C: 'Escribiendo código en vez de los Developers',
      D: 'Priorizando el Product Backlog',
    },
    answer: ['A', 'B'],
    explanation: 'El SM sirve a la organización facilitando adopción, removiendo impedimentos sistémicos y entrenando.',
    domain: 'Roles',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El Sprint Review time-box MÁXIMO para un Sprint de 4 semanas es:',
    options: { A: '1 hora', B: '2 horas', C: '4 horas', D: '8 horas' },
    answer: ['C'],
    explanation: 'Sprint Review: máx 4 horas para Sprint de 1 mes. Proporcional para Sprints más cortos.',
    domain: 'Eventos',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Sprint Planning time-box MÁXIMO para un Sprint de 1 mes:',
    options: { A: '4 horas', B: '6 horas', C: '8 horas', D: '12 horas' },
    answer: ['C'],
    explanation: 'Sprint Planning: hasta 8 horas para un Sprint de 1 mes.',
    domain: 'Eventos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un Developer descubre que no podrá completar un PBI del Sprint. ¿Qué debe hacer?',
    options: {
      A: 'Ocultarlo hasta el Sprint Review',
      B: 'Informar al equipo y renegociar el alcance con el PO',
      C: 'Terminar el Sprint unilateralmente',
      D: 'Pedir una extensión del Sprint',
    },
    answer: ['B'],
    explanation: 'Transparencia: se comunica y se renegocia alcance con el PO. Sprints NO se extienden.',
    domain: 'Sprint',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El Product Backlog está:',
    options: {
      A: 'Completamente planeado desde el día 1',
      B: 'Emergente: evoluciona con el producto y el entendimiento',
      C: 'Es fijo por contrato',
      D: 'Solo lo ve el PO',
    },
    answer: ['B'],
    explanation: 'Es emergente. Los items de arriba son más pequeños y detallados; los de abajo, gruesos.',
    domain: 'Artefactos',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'La transparencia en Scrum se logra mediante:',
    options: {
      A: 'Artefactos claros + commitments',
      B: 'Comités',
      C: 'Reportes al CEO',
      D: 'Software propietario',
    },
    answer: ['A'],
    explanation: 'Artefactos transparentes (PB con Product Goal, SB con Sprint Goal, Increment con DoD) son la base de la inspección.',
    domain: 'Teoría',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El valor de "Foco" en Scrum significa:',
    options: {
      A: 'Enfocarse en el trabajo del Sprint y las metas del Scrum Team',
      B: 'Trabajar solo con un cliente',
      C: 'Usar solo una herramienta',
      D: 'Foco en velocity',
    },
    answer: ['A'],
    explanation: 'Los 5 valores: Compromiso, Foco, Apertura, Respeto, Coraje. Foco = concentrarse en el Sprint.',
    domain: 'Valores',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Burndown charts son:',
    options: {
      A: 'Mandatorios en Scrum',
      B: 'Herramientas opcionales de complementary practices, no parte del marco oficial',
      C: 'Parte del Scrum Guide',
      D: 'Exclusivos del PO',
    },
    answer: ['B'],
    explanation: 'Burndown/burnup NO son parte oficial de Scrum. Son prácticas complementarias útiles pero opcionales.',
    domain: 'Prácticas',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué es el Refinement del Product Backlog?',
    options: {
      A: 'Un evento oficial de Scrum',
      B: 'Una actividad ongoing de desglose, clarificación y estimación de PBIs',
      C: 'Una reunión obligatoria semanal',
      D: 'Responsabilidad solo del PO',
    },
    answer: ['B'],
    explanation: 'Refinement es actividad continua (no evento formal). Típicamente usa ~10% del tiempo del equipo.',
    domain: 'Refinement',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Múltiples Scrum Teams trabajando en un mismo producto deben:',
    options: {
      A: 'Tener PBs separados',
      B: 'Compartir un único Product Backlog, un PO y una DoD común',
      C: 'Tener varios POs',
      D: 'Ser independientes',
    },
    answer: ['B'],
    explanation: 'Scrum de Scrum: un producto, un PB, un PO, una DoD (puede haber DoD por equipo más estricta encima de la común).',
    domain: 'Escalamiento',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Un Increment es:',
    options: {
      A: 'El total de Product Backlog Items "Done" en el Sprint más los de Sprints anteriores',
      B: 'Una feature nueva',
      C: 'Un commit de código',
      D: 'Un release',
    },
    answer: ['A'],
    explanation: 'El Increment es la suma de todos los PBIs completos, integrados, usables y que cumplen la DoD.',
    domain: 'Artefactos',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Se pueden liberar incrementos:',
    options: {
      A: 'Solo al final del Sprint',
      B: 'Durante el Sprint en cualquier momento (releases múltiples posibles)',
      C: 'Solo cada 3 Sprints',
      D: 'Nunca durante el Sprint',
    },
    answer: ['B'],
    explanation: 'Un Increment puede entregarse a stakeholders durante el Sprint. La entrega no está atada al Sprint Review.',
    domain: 'Release',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué NO es responsabilidad del Product Owner?',
    options: {
      A: 'Maximizar el valor del producto',
      B: 'Administrar el Product Backlog',
      C: 'Determinar CÓMO se construye cada PBI',
      D: 'Decidir qué se construye',
    },
    answer: ['C'],
    explanation: 'El CÓMO lo deciden los Developers. El PO decide el QUÉ y el orden.',
    domain: 'Roles',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Durante el Daily Scrum, el SM está:',
    options: {
      A: 'Obligatoriamente presente',
      B: 'Presente solo si los Developers lo piden; no dirige el evento',
      C: 'Dirige el evento',
      D: 'Sustituye al PO',
    },
    answer: ['B'],
    explanation: 'Daily Scrum es del y para los Developers. El SM asegura que ocurra pero no es necesariamente facilitador.',
    domain: 'Eventos',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Si la DoD no existe en la organización:',
    options: {
      A: 'El Scrum Team debe crearla',
      B: 'No se puede hacer Scrum',
      C: 'El PO la impone',
      D: 'Se ignora',
    },
    answer: ['A'],
    explanation: 'Si no hay DoD organizacional, el Scrum Team crea una apropiada para el producto.',
    domain: 'DoD',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Estimaciones de los PBIs son realizadas por:',
    options: {
      A: 'El Scrum Master',
      B: 'Los Developers (quienes harán el trabajo)',
      C: 'El PO',
      D: 'El cliente',
    },
    answer: ['B'],
    explanation: 'Solo quienes harán el trabajo estiman. PO y SM pueden facilitar pero no estiman por los Developers.',
    domain: 'Estimación',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es "velocity"?',
    options: {
      A: 'Una métrica obligatoria del Scrum Guide',
      B: 'Una práctica complementaria: suma de story points completados por Sprint',
      C: 'Tiempo total de trabajo',
      D: 'Número de Daily Scrums',
    },
    answer: ['B'],
    explanation: 'Velocity NO está en la Guide. Es útil internamente, NO para comparar equipos ni como KPI externo.',
    domain: 'Prácticas',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El Scrum Master ayuda al PO a:',
    options: {
      A: 'Definir Product Goal y gestionar el Product Backlog efectivamente',
      B: 'Escribir código',
      C: 'Hacer demos',
      D: 'Reemplazarlo en decisiones',
    },
    answer: ['A'],
    explanation: 'El SM sirve al PO con técnicas de Product Backlog management, Product Goal discovery, facilitación con stakeholders.',
    domain: 'Roles',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'El "coraje" en Scrum significa:',
    options: {
      A: 'Asumir trabajo difícil y tener conversaciones difíciles',
      B: 'Trabajar horas extras',
      C: 'Desafiar al PO siempre',
      D: 'Rechazar stakeholders',
    },
    answer: ['A'],
    explanation: 'Coraje: hacer lo correcto, decir la verdad, asumir trabajo desafiante.',
    domain: 'Valores',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'En la Guide 2020, los eventos de Scrum son:',
    options: {
      A: '3',
      B: '4',
      C: '5 (Sprint, Planning, Daily, Review, Retrospective)',
      D: '7',
    },
    answer: ['C'],
    explanation: 'El Sprint es un contenedor de los otros 4 eventos: Planning, Daily, Review, Retrospective.',
    domain: 'Eventos',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Respecto a los artefactos y commitments (Guide 2020):',
    options: {
      A: 'Product Backlog→Product Goal; Sprint Backlog→Sprint Goal; Increment→Definition of Done',
      B: 'No existen commitments',
      C: 'Solo hay DoD',
      D: 'Los commitments los define el PO',
    },
    answer: ['A'],
    explanation: 'Nuevo en 2020: cada artefacto tiene un commitment asociado para reforzar transparencia.',
    domain: 'Artefactos',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Si el Sprint Goal queda obsoleto a mitad del Sprint:',
    options: {
      A: 'Se continúa igual',
      B: 'El PO tiene autoridad para cancelar el Sprint',
      C: 'El SM lo cancela',
      D: 'El cliente lo cancela',
    },
    answer: ['B'],
    explanation: 'Solo el PO puede cancelar un Sprint cuando el Sprint Goal pierde sentido.',
    domain: 'Sprint',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es "Undone work"?',
    options: {
      A: 'Trabajo que NO cumple la Definition of Done',
      B: 'Trabajo futuro',
      C: 'Bugs',
      D: 'Trabajo cancelado',
    },
    answer: ['A'],
    explanation: 'Undone work: trabajo hecho pero que no cumple criterios de Done; suele requerir remediation.',
    domain: 'DoD',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Cuál es el propósito principal de Scrum?',
    options: {
      A: 'Entregar proyectos en fecha',
      B: 'Gestionar trabajo complejo mediante iteraciones empíricas que generan valor',
      C: 'Reducir costos',
      D: 'Reemplazar otros frameworks',
    },
    answer: ['B'],
    explanation: 'Scrum es un framework ligero para trabajo complejo, basado en empirismo y lean thinking.',
    domain: 'Teoría',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué significa "self-managing" en Scrum (Guide 2020)?',
    options: {
      A: 'El equipo decide QUIÉN, CÓMO y QUÉ trabajar',
      B: 'Solo decide el CÓMO',
      C: 'No decide nada',
      D: 'Lo decide el SM',
    },
    answer: ['A'],
    explanation: 'Guide 2020 reemplazó "self-organizing" por "self-managing": el equipo decide internamente quién, cómo y qué trabaja.',
    domain: 'Equipo Scrum',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Seleccione DOS afirmaciones válidas sobre el Sprint.',
    options: {
      A: 'Un nuevo Sprint inicia inmediatamente después del anterior',
      B: 'La duración es fija y consistente entre Sprints',
      C: 'Se puede extender si no se termina todo',
      D: 'Se salta si no hay trabajo',
    },
    answer: ['A', 'B'],
    explanation: 'Sprint: cadencia fija e ininterrumpida. Nunca se extiende ni salta.',
    domain: 'Sprint',
    difficulty: 'medium',
  },
];

// ════════════════════════════════════════════════════════════════════
// CompTIA Security+ — 35 extras → 50 total
// ════════════════════════════════════════════════════════════════════
const SECURITY_PLUS_EXTRAS = [
  {
    type: 'multiple',
    question: 'Principio de "defense in depth":',
    options: {
      A: 'Un solo control fuerte',
      B: 'Múltiples capas de controles independientes',
      C: 'Cifrado únicamente',
      D: 'Firewall únicamente',
    },
    answer: ['B'],
    explanation: 'Defense in depth usa capas redundantes (firewall + IDS + MFA + training + encriptación + monitoreo).',
    domain: 'Arquitectura',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué ataque intercepta comunicaciones entre dos partes sin que lo sepan?',
    options: { A: 'Man-in-the-Middle (MitM)', B: 'DoS', C: 'Replay', D: 'DNS poisoning' },
    answer: ['A'],
    explanation: 'MitM: el atacante se posiciona entre dos hosts y puede leer/modificar tráfico.',
    domain: 'Ataques',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué tipo de test de penetración tiene conocimiento completo del sistema?',
    options: { A: 'Black-box', B: 'White-box', C: 'Gray-box', D: 'Red team' },
    answer: ['B'],
    explanation: 'White-box: el pentester tiene arquitectura, código fuente, credenciales. Black-box: cero info. Gray-box: info parcial.',
    domain: 'Testing',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Modelo Zero Trust asume:',
    options: {
      A: 'Red interna es confiable',
      B: 'Nunca confiar, siempre verificar: cada request debe autenticarse y autorizarse',
      C: 'Solo MFA',
      D: 'Perímetro fuerte',
    },
    answer: ['B'],
    explanation: 'Zero Trust: "never trust, always verify". No hay red confiable; se autentica y autoriza cada acceso.',
    domain: 'Arquitectura',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'SIEM vs SOAR:',
    options: {
      A: 'Son idénticos',
      B: 'SIEM agrega y correlaciona logs; SOAR orquesta y automatiza respuesta',
      C: 'SOAR analiza; SIEM responde',
      D: 'SIEM es solo cloud',
    },
    answer: ['B'],
    explanation: 'SIEM = detección. SOAR (Security Orchestration, Automation and Response) = respuesta automatizada (playbooks).',
    domain: 'Operaciones',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué algoritmo es recomendado para hashing de passwords modernamente?',
    options: { A: 'MD5', B: 'SHA-1', C: 'bcrypt / Argon2 / scrypt', D: 'CRC32' },
    answer: ['C'],
    explanation: 'Password hashing requiere algoritmos costosos con salt: Argon2 (ganador PHC 2015), bcrypt, scrypt.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un "salt" en hashing de passwords sirve para:',
    options: {
      A: 'Hacer el hash más corto',
      B: 'Evitar ataques de rainbow tables: cada password obtiene hash único',
      C: 'Acelerar el proceso',
      D: 'Comprimir el password',
    },
    answer: ['B'],
    explanation: 'Salt único por password rompe precomputación. Pepper (secreto global) añade capa adicional.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es un ataque de "privilege escalation"?',
    options: {
      A: 'Negación de servicio',
      B: 'Obtener privilegios superiores a los asignados (vertical o horizontal)',
      C: 'Robar credenciales',
      D: 'Phishing',
    },
    answer: ['B'],
    explanation: 'Vertical: de user a admin. Horizontal: de userA a userB.',
    domain: 'Ataques',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS formas de protegerse contra ransomware.',
    options: {
      A: 'Backups inmutables offsite',
      B: 'Parches actualizados y EDR',
      C: 'Abrir adjuntos desconocidos',
      D: 'Desactivar antivirus',
    },
    answer: ['A', 'B'],
    explanation: 'Controles: backups 3-2-1, parches, EDR, training anti-phishing, segmentación, least privilege.',
    domain: 'Malware',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'La regla 3-2-1 de backups dice:',
    options: {
      A: '3 backups, 2 medios distintos, 1 offsite',
      B: '3 días, 2 semanas, 1 año',
      C: '3 usuarios, 2 admins, 1 root',
      D: 'Sin regla formal',
    },
    answer: ['A'],
    explanation: '3 copias (incluyendo original), en ≥2 medios diferentes, con ≥1 fuera del sitio (idealmente offline/inmutable).',
    domain: 'Continuidad',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es CVSS?',
    options: {
      A: 'Un antivirus',
      B: 'Common Vulnerability Scoring System — score 0-10 de severidad',
      C: 'Un protocolo',
      D: 'Un firewall',
    },
    answer: ['B'],
    explanation: 'CVSS v3.1: 0–10. Critical (9.0+), High (7.0-8.9), Medium (4.0-6.9), Low (0.1-3.9).',
    domain: 'Vulnerabilidades',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es un "zero-day"?',
    options: {
      A: 'Vulnerabilidad recién parcheada',
      B: 'Vulnerabilidad desconocida por el vendor y sin parche disponible',
      C: 'Bug cosmético',
      D: 'Un tipo de malware',
    },
    answer: ['B'],
    explanation: 'Zero-day: vulnerabilidad no conocida/parcheada; la explotación es "0-day exploit".',
    domain: 'Vulnerabilidades',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Segregation of Duties (SoD) se usa para:',
    options: {
      A: 'Separar responsabilidades críticas para prevenir fraude/errores',
      B: 'Dividir proyectos',
      C: 'Gestionar equipos',
      D: 'Encriptar datos',
    },
    answer: ['A'],
    explanation: 'SoD: ninguna persona controla todo el proceso crítico (ej. quien autoriza un pago no lo ejecuta).',
    domain: 'Governance',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un honeypot es:',
    options: {
      A: 'Sistema señuelo diseñado para atraer y estudiar atacantes',
      B: 'Firewall',
      C: 'IDS',
      D: 'Backup',
    },
    answer: ['A'],
    explanation: 'Honeypots (individuales) y honeynets (redes) atraen actividad maliciosa para análisis.',
    domain: 'Operaciones',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué protocolo de autenticación usa tickets y es la base de Active Directory?',
    options: { A: 'RADIUS', B: 'TACACS+', C: 'Kerberos', D: 'OAuth' },
    answer: ['C'],
    explanation: 'Kerberos: TGT del KDC permite obtener service tickets. AD lo usa para SSO en Windows domain.',
    domain: 'Autenticación',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'SAML vs OAuth 2.0:',
    options: {
      A: 'Son idénticos',
      B: 'SAML es para SSO federado (XML); OAuth 2.0 es para autorización/delegación (tokens)',
      C: 'OAuth 2.0 es SSO; SAML es autorización',
      D: 'Solo SAML soporta JWT',
    },
    answer: ['B'],
    explanation: 'SAML (XML, enterprise SSO). OAuth 2.0 (tokens, autorización). OpenID Connect = autenticación sobre OAuth 2.0.',
    domain: 'Federación',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué es un ataque pass-the-hash?',
    options: {
      A: 'Capturar el hash NTLM y usarlo para autenticarse sin conocer el password',
      B: 'Romper hashes por fuerza bruta',
      C: 'Man-in-the-middle',
      D: 'DNS spoofing',
    },
    answer: ['A'],
    explanation: 'Pass-the-hash explota NTLM: el hash es suficiente para autenticación; no se necesita el password en claro.',
    domain: 'Ataques',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Hardening de un servidor incluye:',
    options: {
      A: 'Desactivar servicios innecesarios, parches, cuentas por defecto, logs',
      B: 'Solo instalar antivirus',
      C: 'Abrir todos los puertos',
      D: 'Desactivar logs',
    },
    answer: ['A'],
    explanation: 'Hardening reduce superficie de ataque: minimizar servicios, cuentas, permisos, puertos abiertos.',
    domain: 'Hardening',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es un WAF?',
    options: {
      A: 'Web Application Firewall — filtra HTTP L7',
      B: 'Windows Access Firewall',
      C: 'Wireless AP Filter',
      D: 'Web Anti-Fraud',
    },
    answer: ['A'],
    explanation: 'WAF filtra en L7: SQLi, XSS, CSRF, OWASP Top 10 patterns.',
    domain: 'Defensa',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'DLP (Data Loss Prevention) sirve para:',
    options: {
      A: 'Detectar y bloquear exfiltración de datos sensibles',
      B: 'Cifrar discos',
      C: 'Backups',
      D: 'Autenticar usuarios',
    },
    answer: ['A'],
    explanation: 'DLP clasifica datos (PII, financieros) y aplica políticas en endpoints, red y cloud.',
    domain: 'Data Protection',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es un IOC?',
    options: {
      A: 'Indicator of Compromise — evidencia observable de intrusión (hashes, IPs, dominios)',
      B: 'International Organization Cybersecurity',
      C: 'Incident Operations Center',
      D: 'Internal Office Control',
    },
    answer: ['A'],
    explanation: 'IOCs se comparten vía STIX/TAXII y feeds de threat intelligence para detección.',
    domain: 'Threat Intel',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué fase viene primero en el Incident Response según NIST?',
    options: {
      A: 'Preparation',
      B: 'Detection',
      C: 'Recovery',
      D: 'Eradication',
    },
    answer: ['A'],
    explanation: 'NIST SP 800-61: Preparation → Detection & Analysis → Containment, Eradication & Recovery → Post-Incident Activity.',
    domain: 'Incident Response',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué tipo de cifrado usa una clave pública para cifrar y una privada para descifrar?',
    options: { A: 'Simétrico', B: 'Asimétrico', C: 'Hash', D: 'Stream cipher' },
    answer: ['B'],
    explanation: 'Cifrado asimétrico (RSA, ECC). Simétrico usa la misma clave.',
    domain: 'Criptografía',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es una firma digital?',
    options: {
      A: 'Un hash cifrado con la clave PRIVADA del firmante, verificado con la PÚBLICA',
      B: 'Un password',
      C: 'Un certificado',
      D: 'Una cookie',
    },
    answer: ['A'],
    explanation: 'Firma digital garantiza autenticidad (solo el dueño de la privada pudo firmarlo), integridad (hash) y no-repudio.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un ataque DDoS se mitiga principalmente con:',
    options: {
      A: 'Firewall básico',
      B: 'CDN, anti-DDoS scrubbing services, rate limiting y auto-scaling',
      C: 'Desactivar el servicio',
      D: 'Migrar de proveedor',
    },
    answer: ['B'],
    explanation: 'Mitigación: CDN (absorber), scrubbing (Cloudflare/AWS Shield), rate limiting, auto-scaling.',
    domain: 'Ataques',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué puerto usa HTTPS por defecto?',
    options: { A: '80', B: '443', C: '8080', D: '22' },
    answer: ['B'],
    explanation: '443 es HTTPS. 80 es HTTP, 22 es SSH, 8080 es HTTP alternativo.',
    domain: 'Redes',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Para qué se usa SIEM típicamente?',
    options: {
      A: 'Agregar logs de múltiples sistemas, correlacionar eventos y generar alertas',
      B: 'Cifrar datos',
      C: 'Hacer backups',
      D: 'Autenticar usuarios',
    },
    answer: ['A'],
    explanation: 'SIEM centraliza logs/eventos de red, endpoint, aplicación, cloud y detecta amenazas con reglas y ML.',
    domain: 'Operaciones',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es ARP poisoning?',
    options: {
      A: 'Envenenar la tabla ARP local de víctimas para redirigir tráfico L2',
      B: 'Un tipo de virus',
      C: 'Un protocolo de auth',
      D: 'DNS hijacking',
    },
    answer: ['A'],
    explanation: 'ARP spoofing permite MitM en LAN. Mitigación: static ARP, dynamic ARP inspection, 802.1X.',
    domain: 'Redes',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué control mitiga el riesgo de "shoulder surfing"?',
    options: {
      A: 'Filtros de privacidad en pantalla + clean desk policy',
      B: 'Antivirus',
      C: 'Firewall',
      D: 'VPN',
    },
    answer: ['A'],
    explanation: 'Shoulder surfing: espiar pantalla/teclado. Controles físicos y de comportamiento.',
    domain: 'Social Engineering',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS controles criptográficos para datos at-rest.',
    options: {
      A: 'Full Disk Encryption (BitLocker, LUKS)',
      B: 'Transparent Data Encryption (TDE) en BDs',
      C: 'TLS',
      D: 'IPsec',
    },
    answer: ['A', 'B'],
    explanation: 'At-rest: FDE, TDE, S3 SSE, disk-level. TLS/IPsec son in-transit.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un ataque de "smishing" ocurre vía:',
    options: { A: 'Email', B: 'SMS/mensajería móvil', C: 'Voz', D: 'USB' },
    answer: ['B'],
    explanation: 'Smishing = SMS phishing. Vishing = voice phishing. Whaling = targeted a ejecutivos.',
    domain: 'Social Engineering',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es un IDS vs IPS?',
    options: {
      A: 'Son idénticos',
      B: 'IDS detecta y alerta; IPS detecta y bloquea automáticamente',
      C: 'IDS bloquea; IPS alerta',
      D: 'IDS es solo hardware',
    },
    answer: ['B'],
    explanation: 'IDS pasivo (alerta). IPS en línea (puede dropear/reset). Complementan firewalls.',
    domain: 'Defensa',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un atacante usa una USB dejada "olvidada" para infectar máquina. Esto es:',
    options: {
      A: 'Baiting (social engineering)',
      B: 'Phishing',
      C: 'Vishing',
      D: 'Tailgating',
    },
    answer: ['A'],
    explanation: 'Baiting: dejar señuelo (USB) que la víctima conecta. Tailgating: colarse tras alguien que abre puerta.',
    domain: 'Social Engineering',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'La "cadena de custodia" en forensics:',
    options: {
      A: 'Documentación de quién manipuló evidencia y cuándo, para admisibilidad legal',
      B: 'Un protocolo de red',
      C: 'Un tipo de cifrado',
      D: 'Autenticación multi-factor',
    },
    answer: ['A'],
    explanation: 'Chain of custody es crítica para forensics: quién recolectó, cuándo, cómo se almacenó, quién accedió.',
    domain: 'Forensics',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Hashing MD5 debería usarse para:',
    options: {
      A: 'Passwords',
      B: 'Firmas digitales',
      C: 'Checksum no-crítico (compatibilidad legacy únicamente) — NO para seguridad',
      D: 'Certificados TLS',
    },
    answer: ['C'],
    explanation: 'MD5 está roto (colisiones). Solo para detectar corrupción accidental en contextos legacy; nunca para seguridad.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
];

// ════════════════════════════════════════════════════════════════════
// OWASP Top 10 — 38 extras → 50 total
// ════════════════════════════════════════════════════════════════════
const OWASP_EXTRAS = [
  {
    type: 'multiple',
    question: '¿Qué categoría cubre almacenar passwords en texto plano o con algoritmos débiles?',
    options: {
      A: 'A01 Broken Access Control',
      B: 'A02 Cryptographic Failures',
      C: 'A03 Injection',
      D: 'A05 Security Misconfiguration',
    },
    answer: ['B'],
    explanation: 'A02 (antes "Sensitive Data Exposure") incluye criptografía ausente, débil o mal implementada.',
    domain: 'Criptografía',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Prevención de SSRF incluye:',
    options: {
      A: 'Validar/sanitizar URLs, usar allow-lists de destinos, segmentar red',
      B: 'Solo HTTPS',
      C: 'Desactivar logs',
      D: 'CAPTCHA',
    },
    answer: ['A'],
    explanation: 'SSRF: allow-list de hosts permitidos, bloquear IPs internas (169.254.*, 10.*, 127.*), segmentación.',
    domain: 'SSRF',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un HSTS header hace:',
    options: {
      A: 'Forzar al browser a usar solo HTTPS para futuras peticiones al dominio',
      B: 'Cifrar cookies',
      C: 'Bloquear XSS',
      D: 'Autenticar usuarios',
    },
    answer: ['A'],
    explanation: 'Strict-Transport-Security previene downgrade attacks (SSL stripping). Combinable con preload list.',
    domain: 'Defense-in-Depth',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué atributo de cookie previene robo vía JavaScript?',
    options: { A: 'Secure', B: 'HttpOnly', C: 'SameSite', D: 'Path' },
    answer: ['B'],
    explanation: 'HttpOnly: no accesible desde document.cookie. Secure: solo HTTPS. SameSite: CSRF.',
    domain: 'Sesiones',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS atributos clave para cookies de sesión seguras.',
    options: { A: 'HttpOnly', B: 'Secure', C: 'Path', D: 'Expires' },
    answer: ['A', 'B'],
    explanation: 'Mínimo: HttpOnly + Secure + SameSite. Path/Domain son configuración, no seguridad per se.',
    domain: 'Sesiones',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es "deserialización insegura"?',
    options: {
      A: 'Deserializar datos no confiables permitiendo ejecución de código o manipulación de objetos',
      B: 'Usar JSON en vez de XML',
      C: 'Comprimir datos',
      D: 'Encriptar dos veces',
    },
    answer: ['A'],
    explanation: 'Deserialización insegura (parte de A08) puede llevar a RCE. Mitigación: deserialización tipada, firma de payloads.',
    domain: 'A08',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Cuál es el MÁS seguro para almacenar tokens de sesión en SPA?',
    options: {
      A: 'localStorage (vulnerable a XSS)',
      B: 'httpOnly cookie + CSRF token o SameSite=Strict',
      C: 'sessionStorage',
      D: 'En la URL',
    },
    answer: ['B'],
    explanation: 'localStorage es accesible vía JS (vulnerable a XSS). Cookies httpOnly son aisladas del JS.',
    domain: 'Sesiones',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Un output binding unsafe (ej. `innerHTML = userInput`) causa:',
    options: { A: 'SQL Injection', B: 'XSS', C: 'CSRF', D: 'SSRF' },
    answer: ['B'],
    explanation: 'Inyectar HTML/JS en el DOM sin sanitizar causa XSS. Usar textContent o frameworks que auto-escapen.',
    domain: 'Injection',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Prevención de XSS en backend/frontend:',
    options: {
      A: 'Escape contextual (HTML, JS, URL, CSS) + CSP + usar frameworks que auto-escapen',
      B: 'Filtrar la palabra "script"',
      C: 'Solo HTTPS',
      D: 'Cookies HttpOnly',
    },
    answer: ['A'],
    explanation: 'XSS requiere encoding contextual. React/Vue/Angular auto-escapan por defecto. CSP como defensa en profundidad.',
    domain: 'Injection',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es JWT y su riesgo principal?',
    options: {
      A: 'JSON Web Token; principal riesgo: uso de alg:none o claves débiles',
      B: 'Java Web Template',
      C: 'JavaScript Web Tool',
      D: 'Sin riesgos',
    },
    answer: ['A'],
    explanation: 'JWT: usar alg seguro (ej. RS256), NUNCA alg:none, claves fuertes, expiración corta, no almacenar PII en payload.',
    domain: 'Autenticación',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Una API expone campos internos en la respuesta JSON (ej. password_hash). Esto cae en:',
    options: {
      A: 'A02 Cryptographic Failures',
      B: 'A01 Broken Access Control (exposición de datos)',
      C: 'A03 Injection',
      D: 'A07 Auth Failures',
    },
    answer: ['B'],
    explanation: 'Excessive Data Exposure es common en APIs. Mitigación: DTOs explícitos, allow-list de campos.',
    domain: 'API Security',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Cuál es el riesgo principal de "Security Misconfiguration"?',
    options: {
      A: 'Defaults inseguros, admin consoles expuestos, headers ausentes',
      B: 'SQL Injection',
      C: 'XSS',
      D: 'Phishing',
    },
    answer: ['A'],
    explanation: 'A05: configuración por defecto, permisos excesivos, verbosidad de errores, admin expuestos, headers de seguridad ausentes.',
    domain: 'Config',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS headers de seguridad que deberías configurar.',
    options: {
      A: 'Content-Security-Policy',
      B: 'X-Frame-Options',
      C: 'Server: Apache/1.0',
      D: 'X-Powered-By',
    },
    answer: ['A', 'B'],
    explanation: 'Añadir: CSP, X-Frame-Options, HSTS, X-Content-Type-Options. Eliminar: Server, X-Powered-By.',
    domain: 'Defense-in-Depth',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Prevención de CSRF:',
    options: {
      A: 'Tokens anti-CSRF + SameSite cookies + verificación de Origin/Referer',
      B: 'Solo HTTPS',
      C: 'Firewall',
      D: 'Antivirus',
    },
    answer: ['A'],
    explanation: 'CSRF: anti-CSRF tokens (synchronizer/double-submit), SameSite=Strict/Lax, check Origin.',
    domain: 'CSRF',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es SRI (Subresource Integrity)?',
    options: {
      A: 'Hash integridad de scripts/styles externos en el atributo `integrity`',
      B: 'Un framework',
      C: 'Un protocolo',
      D: 'Un firewall',
    },
    answer: ['A'],
    explanation: 'SRI previene que un CDN comprometido sirva contenido alterado: el browser valida el hash.',
    domain: 'Supply Chain',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Un ataque de "command injection":',
    options: {
      A: 'Ejecutar comandos del sistema operativo al pasar input sin sanitizar a shell',
      B: 'Inyectar SQL',
      C: 'Inyectar HTML',
      D: 'Inyectar LDAP',
    },
    answer: ['A'],
    explanation: 'Ocurre cuando input se concatena en `exec()`/`system()`. Mitigación: APIs paramétricas, jamás shell=True.',
    domain: 'Injection',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Path traversal permite:',
    options: {
      A: 'Acceder a archivos fuera del directorio esperado con "../"',
      B: 'Ejecutar SQL',
      C: 'Inyectar XSS',
      D: 'Cambiar DNS',
    },
    answer: ['A'],
    explanation: 'Mitigación: normalizar path, validar contra allow-list, usar librerías seguras.',
    domain: 'Injection',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'XXE (XML External Entity) attack:',
    options: {
      A: 'Abusar entidades externas en XML para leer archivos locales o hacer SSRF',
      B: 'Inyectar JSON',
      C: 'Phishing por XML',
      D: 'Error de DTD',
    },
    answer: ['A'],
    explanation: 'XXE: <!ENTITY x SYSTEM "file:///etc/passwd">. Mitigación: deshabilitar external entities, usar DOM-only parser.',
    domain: 'Injection',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué técnica protege contra fuerza bruta en login?',
    options: {
      A: 'Rate limiting + account lockout progresivo + MFA',
      B: 'Deshabilitar password',
      C: 'Hash más largo',
      D: 'Logs más detallados',
    },
    answer: ['A'],
    explanation: 'Rate limit por IP/user, lockout temporal, CAPTCHA, MFA, monitoring de anomalías.',
    domain: 'Autenticación',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: '¿Qué es "credential stuffing"?',
    options: {
      A: 'Usar credenciales filtradas de otros sites para probar en muchos servicios',
      B: 'Brute force',
      C: 'Phishing',
      D: 'SQL Injection',
    },
    answer: ['A'],
    explanation: 'Credential stuffing explota reuso de passwords. Mitigación: MFA, detección de bots, pwned password checks.',
    domain: 'Ataques',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS prácticas recomendadas para APIs.',
    options: {
      A: 'Rate limiting por usuario/IP',
      B: 'Versionado y schema explícito (ej. OpenAPI)',
      C: 'Exponer stack traces en producción',
      D: 'Usar IDs incrementales sin verificación',
    },
    answer: ['A', 'B'],
    explanation: 'A01/A04 mitigados con schemas, versionado, rate limit, autorización por recurso.',
    domain: 'API Security',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué herramienta analiza código fuente para detectar vulnerabilidades?',
    options: {
      A: 'SAST (Static Application Security Testing)',
      B: 'DAST',
      C: 'RASP',
      D: 'SIEM',
    },
    answer: ['A'],
    explanation: 'SAST: análisis estático (Semgrep, SonarQube, Checkmarx). DAST: dinámico (ZAP, Burp).',
    domain: 'Testing',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'DAST complementa a SAST porque:',
    options: {
      A: 'Ejecuta la aplicación y prueba endpoints en runtime (sin ver código)',
      B: 'Analiza código',
      C: 'Monitorea logs',
      D: 'Hace backups',
    },
    answer: ['A'],
    explanation: 'DAST (OWASP ZAP, Burp) ataca la app corriendo. Encuentra config issues, business logic flaws.',
    domain: 'Testing',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué significa el principio "fail securely"?',
    options: {
      A: 'Cuando algo falla, el sistema debe denegar por defecto (fail closed)',
      B: 'Fallar rápido',
      C: 'Ignorar errores',
      D: 'Mostrar stack traces',
    },
    answer: ['A'],
    explanation: 'Fail securely: si la validación/autorización falla, denegar en vez de permitir.',
    domain: 'Principios',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es OWASP ASVS?',
    options: {
      A: 'Application Security Verification Standard — checklist de requisitos para apps',
      B: 'Un escáner',
      C: 'Un framework',
      D: 'Un vendor',
    },
    answer: ['A'],
    explanation: 'ASVS define niveles L1 (básico), L2 (estándar), L3 (crítico) con requisitos verificables.',
    domain: 'Estándares',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Un "open redirect" es:',
    options: {
      A: 'Endpoint que redirige a URL controlada por input sin validar → abusable para phishing',
      B: 'Un error 404',
      C: 'Una redirección HTTPS',
      D: 'Un proxy',
    },
    answer: ['A'],
    explanation: 'Open redirect: /login?next=evil.com. Mitigación: allow-list de dominios destino.',
    domain: 'Web',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Un atacante sube un archivo PHP camuflado como imagen. Esto es:',
    options: {
      A: 'Unrestricted File Upload (A04 Insecure Design + A05 Misconfiguration)',
      B: 'XSS',
      C: 'CSRF',
      D: 'SSRF',
    },
    answer: ['A'],
    explanation: 'Mitigación: validar content-type real, renombrar, almacenar fuera del webroot, escanear con antivirus.',
    domain: 'File Upload',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: '¿Qué herramienta es recomendada por OWASP para pentest web gratuita?',
    options: { A: 'OWASP ZAP', B: 'Wireshark', C: 'nmap', D: 'Hydra' },
    answer: ['A'],
    explanation: 'OWASP Zed Attack Proxy (ZAP) es pentest tool open source mantenida por OWASP.',
    domain: 'Herramientas',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Cifrar datos en tránsito requiere:',
    options: {
      A: 'TLS 1.2+ con cipher suites modernos',
      B: 'Base64',
      C: 'MD5',
      D: 'Solo IP whitelist',
    },
    answer: ['A'],
    explanation: 'TLS 1.2/1.3 con forward secrecy (ECDHE). Deprecated: SSL 3.0, TLS 1.0/1.1.',
    domain: 'Criptografía',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Rotación de claves criptográficas es importante porque:',
    options: {
      A: 'Limita la ventana de exposición si una clave es comprometida',
      B: 'Hace el sistema más rápido',
      C: 'Reduce costos',
      D: 'Es obligatorio para UI',
    },
    answer: ['A'],
    explanation: 'Rotación periódica reduce impacto de compromiso. KMS/HSM suelen facilitarlo.',
    domain: 'Criptografía',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Gestión de secretos en CI/CD:',
    options: {
      A: 'Usar secret managers (Vault, AWS Secrets Manager, GH Secrets) — NUNCA en código ni en logs',
      B: 'Hardcodear en el repo',
      C: 'Variables de entorno en README',
      D: 'Compartir por Slack',
    },
    answer: ['A'],
    explanation: 'Secretos nunca en git. Usar secret stores + rotación + auditoría de acceso.',
    domain: 'DevSecOps',
    difficulty: 'easy',
  },
  {
    type: 'multiple',
    question: 'Una app genera tokens con `Math.random()`. Problema:',
    options: {
      A: 'Math.random no es criptográficamente seguro — usar crypto.randomBytes / CSPRNG',
      B: 'Es lento',
      C: 'No compatible con IE',
      D: 'Consume mucha memoria',
    },
    answer: ['A'],
    explanation: 'CSPRNG requerido para tokens de seguridad: crypto.randomBytes (Node), SecureRandom (Java), secrets (Python).',
    domain: 'Criptografía',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Defensa contra IDOR:',
    options: {
      A: 'Verificar ownership/autorización en cada request — no confiar en IDs del cliente',
      B: 'Usar UUIDs solamente',
      C: 'Solo HTTPS',
      D: 'Ofuscar IDs',
    },
    answer: ['A'],
    explanation: 'IDOR: autorización server-side por objeto. UUIDs ayudan por obscurity pero no son suficientes.',
    domain: 'Access Control',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS prácticas de supply chain security.',
    options: {
      A: 'SBOM y verificación de firmas/hashes de dependencias',
      B: 'Dependabot/Renovate + auditorías (npm audit)',
      C: 'Instalar cualquier versión última',
      D: 'Desactivar lock files',
    },
    answer: ['A', 'B'],
    explanation: 'A08: SBOM, firma de artefactos, pin de versiones, lock files, auditorías automáticas.',
    domain: 'Supply Chain',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: 'Logging & Monitoring: ¿qué eventos se deben registrar?',
    options: {
      A: 'Auth failures, access denied, cambios de permisos, errores del servidor',
      B: 'Solo errores 500',
      C: 'Nada por privacidad',
      D: 'Solo acceso HTTP',
    },
    answer: ['A'],
    explanation: 'A09: eventos de seguridad + correlación. NUNCA log passwords/tokens/PII. Logs append-only.',
    domain: 'Monitoring',
    difficulty: 'medium',
  },
  {
    type: 'multiple',
    question: '¿Qué es RASP?',
    options: {
      A: 'Runtime Application Self-Protection — instrumenta la app para detectar y bloquear ataques en runtime',
      B: 'Un firewall perimetral',
      C: 'Un escáner estático',
      D: 'Un SIEM',
    },
    answer: ['A'],
    explanation: 'RASP se ejecuta dentro de la app, con contexto para bloquear ataques en tiempo real (ej. inyecciones, deserialización).',
    domain: 'Defensa',
    difficulty: 'hard',
  },
  {
    type: 'multiple',
    question: 'Selecciona DOS validaciones que DEBEN hacerse server-side.',
    options: {
      A: 'Autorización de acciones por rol',
      B: 'Validación de integridad y formato de datos',
      C: 'Tamaño de texto en UI',
      D: 'Color del botón',
    },
    answer: ['A', 'B'],
    explanation: 'Client-side es UX. Server-side es seguridad: autorización, validación, integridad, idempotencia.',
    domain: 'Arquitectura',
    difficulty: 'easy',
  },
];

// ────────────────────────────────────────────────────────────────────
// Export: map of slug → extra questions
// ────────────────────────────────────────────────────────────────────
export const EXTRA_QUESTIONS = {
  'aws-solutions-architect-associate': AWS_SAA_EXTRAS,
  'scrum-master-psm-i': SCRUM_PSM_EXTRAS,
  'comptia-security-plus': SECURITY_PLUS_EXTRAS,
  'owasp-top-10': OWASP_EXTRAS,
};
