/**
 * Logic / Aptitude reasoning set.
 *
 * Original questions — classical reasoning patterns (public-domain methodology).
 */

export const LOGIC_SETS = [
  {
    slug: 'razonamiento-logico-basico',
    title: 'Razonamiento Lógico — Básico',
    description:
      'Aptitud numérica, verbal y series lógicas. Útil para pruebas psicotécnicas y de ingreso.',
    domain: 'logic',
    category: 'aptitude',
    level: 'beginner',
    language: 'es',
    tags: ['logica', 'psicotecnico', 'aptitud', 'razonamiento'],
    passPercent: 60,
    timeMinutes: 25,
    source: 'Original — Patrones clásicos de razonamiento (dominio público)',
    questions: [
      {
        type: 'multiple',
        question: 'Complete la serie: 2, 4, 8, 16, __',
        options: { A: '24', B: '30', C: '32', D: '64' },
        answer: ['C'],
        explanation: 'Cada término se duplica: 16 × 2 = 32.',
        domain: 'Series Numéricas',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Si TODOS los perros ladran y Rex es un perro, entonces:',
        options: {
          A: 'Rex puede ladrar o no',
          B: 'Rex ladra',
          C: 'Solo los perros grandes ladran',
          D: 'No se puede concluir nada',
        },
        answer: ['B'],
        explanation: 'Silogismo válido: premisa universal + particular.',
        domain: 'Silogismos',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          'Un tren recorre 240 km en 3 horas. ¿Cuál es su velocidad media?',
        options: { A: '60 km/h', B: '80 km/h', C: '100 km/h', D: '120 km/h' },
        answer: ['B'],
        explanation: 'v = d/t = 240/3 = 80 km/h.',
        domain: 'Problemas de Velocidad',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          '¿Qué número falta? 3, 6, 12, __, 48',
        options: { A: '18', B: '20', C: '24', D: '36' },
        answer: ['C'],
        explanation: 'Cada término se duplica: 12 × 2 = 24.',
        domain: 'Series Numéricas',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          'En un aula hay 30 estudiantes. 18 estudian inglés, 12 francés y 5 ambos. ¿Cuántos no estudian ningún idioma?',
        options: { A: '3', B: '5', C: '7', D: '10' },
        answer: ['B'],
        explanation:
          'Inclusión-exclusión: 18 + 12 − 5 = 25 estudian al menos uno. 30 − 25 = 5 no estudian ninguno.',
        domain: 'Conjuntos',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question:
          '"Libro" es a "leer" como "música" es a:',
        options: { A: 'ver', B: 'escuchar', C: 'tocar', D: 'cantar' },
        answer: ['B'],
        explanation: 'Analogía de acción principal asociada.',
        domain: 'Analogías',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          'Si A > B y B > C, entonces:',
        options: {
          A: 'A < C',
          B: 'A > C',
          C: 'A = C',
          D: 'No se puede determinar',
        },
        answer: ['B'],
        explanation: 'Propiedad transitiva de las desigualdades.',
        domain: 'Lógica Deductiva',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          'Un producto cuesta $120. Con un 25% de descuento, el precio final es:',
        options: { A: '$90', B: '$95', C: '$100', D: '$105' },
        answer: ['A'],
        explanation: '120 × 0.75 = 90. O bien 120 − 30 (25%) = 90.',
        domain: 'Porcentajes',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question:
          '5 obreros construyen un muro en 6 días. ¿Cuántos días necesitan 10 obreros trabajando al mismo ritmo?',
        options: { A: '2', B: '3', C: '4', D: '12' },
        answer: ['B'],
        explanation:
          'Relación inversa: más obreros, menos días. 5×6 = 10×x → x = 3.',
        domain: 'Regla de Tres Inversa',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Complete: JUEVES es a SEMANA como MARZO es a:',
        options: { A: 'DÍA', B: 'MES', C: 'AÑO', D: 'ESTACIÓN' },
        answer: ['C'],
        explanation:
          'Jueves es un elemento de la semana; marzo es un elemento del año.',
        domain: 'Analogías',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Complete la serie: 1, 1, 2, 3, 5, 8, __',
        options: { A: '11', B: '12', C: '13', D: '10' },
        answer: ['C'],
        explanation: 'Es la secuencia de Fibonacci: cada término es la suma de los dos anteriores. 5+8=13.',
        domain: 'Series Numéricas',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Si ningún reptil tiene plumas y la serpiente es un reptil, entonces:',
        options: { A: 'La serpiente puede tener plumas', B: 'La serpiente no tiene plumas', C: 'Algunos reptiles tienen plumas', D: 'No se puede concluir nada' },
        answer: ['B'],
        explanation: 'Silogismo válido: premisa universal negativa aplicada a un caso particular (la serpiente, que es reptil) da una conclusión negativa certera.',
        domain: 'Silogismos',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Un ciclista recorre 150 km en 2.5 horas. ¿Cuál es su velocidad media?',
        options: { A: '50 km/h', B: '55 km/h', C: '60 km/h', D: '65 km/h' },
        answer: ['C'],
        explanation: 'v = d/t = 150/2.5 = 60 km/h.',
        domain: 'Problemas de Velocidad',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: '¿Qué número falta? 100, 50, 25, __, 6.25',
        options: { A: '10', B: '12.5', C: '15', D: '20' },
        answer: ['B'],
        explanation: 'Cada término se divide entre 2: 25/2=12.5.',
        domain: 'Series Numéricas',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'En una encuesta a 50 personas, 30 prefieren café, 25 prefieren té y 10 prefieren ambos. ¿Cuántas no prefieren ninguna de las dos bebidas?',
        options: { A: '3', B: '5', C: '7', D: '10' },
        answer: ['B'],
        explanation: 'Inclusión-exclusión: 30+25-10=45 prefieren al menos una. 50-45=5 no prefieren ninguna.',
        domain: 'Conjuntos',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: '"Pintor" es a "cuadro" como "escultor" es a:',
        options: { A: 'pincel', B: 'escultura', C: 'museo', D: 'piedra' },
        answer: ['B'],
        explanation: 'La relación es "creador → obra creada": el pintor crea un cuadro, el escultor crea una escultura.',
        domain: 'Analogías',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Si P > Q, Q = R, y R > S, ¿cuál es la relación entre P y S?',
        options: { A: 'P < S', B: 'P > S', C: 'P = S', D: 'No se puede determinar' },
        answer: ['B'],
        explanation: 'Por transitividad: P > Q = R > S, por lo tanto P > S.',
        domain: 'Lógica Deductiva',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Un artículo cuesta $80.000. Con un 30% de descuento, ¿cuál es el precio final?',
        options: { A: '$50.000', B: '$54.000', C: '$56.000', D: '$60.000' },
        answer: ['C'],
        explanation: '80.000 × 0.70 = 56.000.',
        domain: 'Porcentajes',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: '8 pintores pintan una casa en 10 días. ¿Cuántos días necesitan 4 pintores trabajando al mismo ritmo?',
        options: { A: '5', B: '15', C: '20', D: '16' },
        answer: ['C'],
        explanation: 'Relación inversa: 8×10 = 4×x → x = 80/4 = 20 días.',
        domain: 'Regla de Tres Inversa',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Complete: HOJA es a ÁRBOL como PÉTALO es a:',
        options: { A: 'JARDÍN', B: 'FLOR', C: 'RAÍZ', D: 'SEMILLA' },
        answer: ['B'],
        explanation: 'La relación es "parte → todo del que forma parte": la hoja es parte del árbol, el pétalo es parte de la flor.',
        domain: 'Analogías',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'En una fila de 4 personas, Ana está justo delante de Beto, y Carla está justo delante de Ana. Si Diego está al final de la fila, ¿cuál es el orden completo de la fila?',
        options: { A: 'Carla, Ana, Beto, Diego', B: 'Ana, Carla, Beto, Diego', C: 'Diego, Carla, Ana, Beto', D: 'Carla, Beto, Ana, Diego' }, answer: ['A'],
        explanation: 'Carla debe ir justo antes que Ana, y Ana justo antes que Beto, formando el bloque "Carla, Ana, Beto"; como Diego está al final, el único orden que cumple todas las condiciones es Carla, Ana, Beto, Diego.',
        domain: 'Lógica Deductiva',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: '¿Qué número falta? 7, 14, 28, 56, __',
        options: { A: '84', B: '112', C: '100', D: '120' },
        answer: ['B'],
        explanation: 'Cada término se duplica: 56 × 2 = 112.',
        domain: 'Series Numéricas',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Si todos los estudiantes de la clase aprobaron el examen y María es estudiante de esa clase, entonces:',
        options: { A: 'María puede haber aprobado o no', B: 'María aprobó el examen', C: 'María es la mejor de la clase', D: 'No se puede concluir nada sobre María' },
        answer: ['B'],
        explanation: 'Silogismo válido: la premisa universal ("todos aprobaron") aplicada a un caso particular (María, que es de esa clase) garantiza la conclusión.',
        domain: 'Silogismos',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Un avión recorre 900 km en 1.5 horas. ¿Cuál es su velocidad media?',
        options: { A: '500 km/h', B: '550 km/h', C: '600 km/h', D: '650 km/h' },
        answer: ['C'],
        explanation: 'v = d/t = 900/1.5 = 600 km/h.',
        domain: 'Problemas de Velocidad',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'De 40 clientes, 22 compran producto A, 18 compran producto B y 8 compran ambos. ¿Cuántos no compran ninguno de los dos productos?',
        options: { A: '6', B: '8', C: '10', D: '12' },
        answer: ['B'],
        explanation: 'Inclusión-exclusión: 22+18-8=32 compran al menos uno. 40-32=8 no compran ninguno.',
        domain: 'Conjuntos',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Un producto cuesta $200.000. Se le aplica un aumento del 12%. ¿Cuál es el nuevo precio?',
        options: { A: '$212.000', B: '$220.000', C: '$224.000', D: '$230.000' },
        answer: ['C'],
        explanation: 'El 12% de 200.000 es 24.000; sumando, el nuevo precio es 200.000+24.000=224.000.',
        domain: 'Porcentajes',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: '6 obreros construyen un muro en 9 días. ¿Cuántos obreros se necesitan para construirlo en 3 días (mismo rendimiento)?',
        options: { A: '12', B: '15', C: '18', D: '20' },
        answer: ['C'],
        explanation: 'Relación inversa: 6×9 = x×3 → x = 54/3 = 18 obreros.',
        domain: 'Regla de Tres Inversa',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Complete: RUEDA es a BICICLETA como ALA es a:',
        options: { A: 'CIELO', B: 'AVIÓN', C: 'PLUMA', D: 'VIENTO' },
        answer: ['B'],
        explanation: 'La relación es "parte → todo del que forma parte": la rueda es parte de la bicicleta, el ala es parte del avión.',
        domain: 'Analogías',
        difficulty: 'easy',
      },
      {
        type: 'multiple',
        question: 'Si X = Y, Y > Z, y Z = W, ¿cuál es la relación entre X y W?',
        options: { A: 'X < W', B: 'X > W', C: 'X = W', D: 'No se puede determinar' },
        answer: ['B'],
        explanation: 'Por transitividad: X = Y > Z = W, por lo tanto X > W.',
        domain: 'Lógica Deductiva',
        difficulty: 'medium',
      },
      {
        type: 'multiple',
        question: 'Complete la serie: 81, 27, 9, 3, __',
        options: { A: '0', B: '1', C: '2', D: '-3' },
        answer: ['B'],
        explanation: 'Cada término se divide entre 3: 3/3=1.',
        domain: 'Series Numéricas',
        difficulty: 'easy',
      },
    ],
  },
];
