/**
 * Catálogo de exámenes a generar mediante LLM.
 * Cada entrada define metadata + temas; el script generate-sets.mjs
 * genera 50 preguntas originales por examen y escribe scripts/seed-data/sets-<batch>.mjs
 *
 * batch = nombre del archivo de salida (agrupa varios exámenes)
 */

/**
 * Fuentes oficiales de referencia por slug.
 * El generador inyecta esta referencia en el prompt para garantizar grounding factual.
 * El LLM DEBE basar el contenido en estos estándares reales — no inventar conceptos.
 */
export const EXAM_SOURCES = {
  // SPORTS
  'nsca-cscs-fundamentos':          'NSCA CSCS Exam Content Description (4th Edition) — nsca.com/certification/cscs',
  'crossfit-level1-basics':         'CrossFit Level 1 Training Guide — crossfit.com/cf-info/cf-certifications',
  'pilates-instructor-basico':      'BASI Pilates Comprehensive Course Curriculum — basipilates.com',
  'yoga-ryt200-fundamentos':        'Yoga Alliance RYT-200 Standards and Curriculum — yogaalliance.org',
  'entrenamiento-fuerza-resistencia': 'ACSM Guidelines for Exercise Testing and Prescription (11th Ed) + NSCA Essentials of Strength Training',
  'nutricion-deportiva-basica':     'ISSN Position Stands: Nutrition and Athletic Performance — jissn.biomedcentral.com',
  'primeros-auxilios-deportivos':   'Red Cross Sports Safety Training + NATA Athletic Training Standards',
  'futbol-entrenador-basico':       'FIFA Coaching Manual (grassroots) + Reglamento de juego FIFA 2023/24',
  'atletismo-fundamentos':          'World Athletics Technical Rules 2024 + IAAF Coaching Education Level 1',
  'natacion-instructor':            'Reglamento World Aquatics (FINA) 2023 + Red Cross Water Safety Instructor Manual',

  // HEALTH
  'bls-basic-life-support':         'AHA BLS Provider Manual 2020 Guidelines — cpr.heart.org',
  'acls-advanced-cardiac':          'AHA ACLS Provider Manual 2020 Guidelines — cpr.heart.org',
  'farmacologia-basica':            'Goodman & Gilman\'s Pharmacological Basis of Therapeutics (14th Ed)',
  'enfermeria-clinica-basica':      'Fundamentals of Nursing — Potter & Perry (10th Ed)',
  'nclex-rn-fundamentos':           'NCLEX-RN Detailed Test Plan 2023 — ncsbn.org/nclex',
  'nutricion-clinica-basica':       'ASPEN Clinical Guidelines + Krause\'s Food & the Nutrition Care Process (15th Ed)',
  'salud-mental-basica':            'DSM-5-TR (APA 2022) + OMS CIE-11 capítulo de trastornos mentales',
  'ecg-interpretacion-basica':      'AHA/ACC ECG Interpretation Guidelines + Dubin\'s Rapid Interpretation of EKGs (7th Ed)',
  'pediatria-basica':               'Nelson Textbook of Pediatrics (21st Ed) + OPS/OMS AIEPI guías clínicas',
  'primeros-auxilios-avanzados':    'Cruz Roja Internacional First Aid Guidelines 2020 + PHTLS 10th Ed',

  // BUSINESS
  'google-analytics-4-certified':   'Google Analytics 4 Certification Exam Guide — skillshop.google.com/c/ga4',
  'google-ads-search-certified':    'Google Ads Search Certification Exam Guide — skillshop.google.com',
  'meta-blueprint-certified':       'Meta Blueprint Digital Marketing Associate Exam Guide — facebook.com/business/learn',
  'hubspot-inbound-marketing':      'HubSpot Inbound Marketing Certification Course — academy.hubspot.com',
  'salesforce-admin-adm201':        'Salesforce Certified Platform Administrator (renombrado desde "Certified Administrator"), blueprint actualizado 15-dic-2025 — 7 dominios, Data & Analytics ahora el mayor (17%), nuevo dominio Agentforce AI incorporado — trailhead.salesforce.com',
  'digital-marketing-fundamentals': 'Google Digital Marketing & E-commerce Certificate (Coursera) + IAB Digital Marketing Certification',
  'seo-fundamentals':               'Google Search Central Documentation — developers.google.com/search + Moz SEO Learning Center',
  'email-marketing-fundamentals':   'Mailchimp Email Marketing Fundamentals + HubSpot Email Marketing Certification',
  'product-management-basics':      'AIPMM Certified Product Manager Body of Knowledge + Marty Cagan "Inspired" (2nd Ed)',
  'data-analytics-google-certificate': 'Google Data Analytics Professional Certificate Curriculum — coursera.org/google-data-analytics',

  // CLOUD EXTENDED
  'aws-developer-associate':        'AWS Certified Developer Associate Exam Guide DVA-C02 — aws.amazon.com/certification/certified-developer-associate',
  'aws-sysops-administrator':       'AWS Certified SysOps Administrator Exam Guide SOA-C02 — aws.amazon.com/certification',
  'azure-administrator-az104':      'Microsoft AZ-104 Exam Skills Outline — learn.microsoft.com/certifications/azure-administrator',
  'gcp-cloud-digital-leader':       'Google Cloud Digital Leader Exam Guide — cloud.google.com/certification/cloud-digital-leader',
  'terraform-associate':            'HashiCorp Certified: Terraform Associate (004), vigente desde ene-2026 (reemplazó a la 003) — 8 dominios oficiales (IaC, Fundamentals, Core Workflow, Configuration, Modules, State Management, Maintain Infrastructure, HCP Terraform), 60 min, ~57-60 preguntas — developer.hashicorp.com/certifications/infrastructure-automation',
  'azure-developer-az204':          'Microsoft AZ-204 Exam Skills Outline — learn.microsoft.com/certifications/azure-developer',
  'comptia-network-plus':           'CompTIA Network+ N10-009 (V9), vigente desde jun-2024 — 5 dominios: Networking Fundamentals 24%, Network Implementations 19%, Network Operations 16%, Network Security, Network Troubleshooting 22% — certmaster.comptia.org',
  'rest-api-design':                'RESTful API Design Guidelines: RFC 7231 (HTTP Semantics) + OpenAPI Specification 3.1',

  // DEVOPS / PROGRAMMING
  'python-pcep-beginner':           'PCEP-30-02 Exam Syllabus — pythoninstitute.org/certification/pcep-certification',
  'python-pcap-intermediate':       'PCAP-31-03 Exam Syllabus — pythoninstitute.org/certification/pcap-certification',
  'javascript-fundamentals':        'ECMAScript 2023 Specification (ECMA-262) + MDN Web Docs — developer.mozilla.org/javascript',
  'java-foundations':               'Oracle Java SE Foundations Exam 1Z0-811 Objectives — education.oracle.com',
  'mongodb-developer-basics':       'MongoDB Certified Developer Associate Exam Guide — university.mongodb.com',
  'postgresql-fundamentals':        'PostgreSQL 16 Official Documentation — postgresql.org/docs + pgexercises.com',
  'devops-fundamentals':            'DORA DevOps Research 2023 + Accelerate (Forsgren et al.) + CALMS framework',
  'ansible-fundamentals':           'Red Hat DO007 Ansible Essentials + Ansible Official Documentation — docs.ansible.com',
  'jenkins-fundamentals':           'CloudBees Jenkins Engineer Certification Study Guide + Jenkins Documentation — jenkins.io',
  'redis-fundamentals':             'Redis Official Documentation — redis.io/docs + Redis University RU101',
  'git-advanced':                   'Pro Git Book (Chacon & Straub, 2nd Ed, free at git-scm.com/book) + GitHub Documentation',

  // ENGLISH
  'english-b2-upper-intermediate':  'CEFR B2 Can-Do Descriptors — coe.int + Cambridge B2 First (FCE) Exam Specifications',
  'english-c1-advanced':            'CEFR C1 Can-Do Descriptors — coe.int + Cambridge C1 Advanced (CAE) Exam Specifications',
  'ielts-academic-reading':         'IELTS Academic Test Format — ielts.org/test-format + Cambridge IELTS 18 Academic',
  'ielts-academic-writing':         'IELTS Academic Writing Band Descriptors (Public Version) — ielts.org',
  'toefl-ibt-fundamentals':         'TOEFL iBT Test Content & Structure — ets.org/toefl + Official TOEFL iBT Tests Volume 1',
  'toeic-listening-reading':        'TOEIC Listening & Reading Test Format — ets.org/toeic + Official TOEIC Practice Tests',
  'business-english-b2':            'CEFR B2 Business Context Descriptors + Cambridge Business English Certificate (BEC) Vantage',
  'english-grammar-advanced':       'A Student\'s Grammar of the English Language (Greenbaum & Quirk) + Cambridge Grammar in Use Advanced',
  'academic-vocabulary-advanced':   'Academic Word List (Coxhead 2000) + Oxford Academic Vocabulary Practice C1-C2',
  'english-pronunciation-phonetics':'Roach: English Phonetics and Phonology (4th Ed) + IPA Chart — internationalphoneticalphabet.org',

  // AGILE EXTENDED
  'pspo-fundamentos':               'Scrum.org PSPO I Assessment Study Guide + The Scrum Guide 2020 — scrumguides.org',
  'safe-scrum-master':              'SAFe 6.0 Scrum Master Certification Exam Study Guide — scaledagile.com/certification',
  'kanban-management-professional': 'Kanban University KMP I Certification Content + "Kanban" book by David Anderson',
  'prince2-foundation':             'PRINCE2 7th Edition Manual — axelos.com/certifications/prince2 + official exam specimen paper',
  'lean-six-sigma-yellow-belt':     'ASQ Lean Six Sigma Yellow Belt Body of Knowledge — asq.org/cert/six-sigma-yellow-belt',
  'scrum-product-owner-pspo':       'Scrum.org Professional Scrum Product Owner I (PSPO I) + The Scrum Guide 2020 — scrumguides.org',
  'pmi-capm-fundamentals':          'PMI CAPM Examination Content Outline (2023), vigente en 2026 — 4 dominios: Fundamentals 36%, Predictive 17%, Agile 20%, Business Analysis 27% — pmi.org/certifications/associate-in-project-management-capm',
  'design-thinking-fundamentals':   'IDEO Design Thinking Framework (5 etapas) + Nielsen Norman Group — nngroup.com/articles/design-thinking',
  'agile-coaching-basics':          'ICAgile ICP-ACC Competency Framework — icagile.com',
  'capm-fundamentos':               'PMI CAPM Exam Content Outline 2023 — pmi.org/certifications/associate-in-project-management-capm',
  'design-thinking-basico':         'IDEO Design Thinking Framework + Nielsen Norman Group Design Thinking (nngroup.com/articles/design-thinking)',
  'agile-coaching-basico':          'ICAgile ICP-ACC Certification Competency Framework — icagile.com',

  // SECURITY EXTENDED
  'ceh-ethical-hacking':            'EC-Council CEH v12 Exam Blueprint — eccouncil.org/programs/certified-ethical-hacker-ceh',
  'cissp-fundamentos':              'ISC2 CISSP Exam Outline 2024 (8 domains) — isc2.org/certifications/cissp',
  'certified-ethical-hacker-basics': 'EC-Council CEH v13 (312-50) Exam Blueprint v5.0, vigente desde sep-2024 — eccouncil.org/programs/certified-ethical-hacker-ceh',
  'cissp-domain-fundamentals':      '(ISC)² CISSP Common Body of Knowledge (CBK), actualizado abr-2024, vigente en 2026 — isc2.org/certifications/cissp',
  'penetration-testing-basics':     'PTES (Penetration Testing Execution Standard) + eLearnSecurity ePPT Syllabus',
  'network-security-fundamentals':  'CompTIA Security+ SY0-701 Exam Objectives + NIST SP 800-53 Rev 5',
  'cloud-security-fundamentals':    'CCSP Exam Outline 2024 — isc2.org/certifications/ccsp + CSA Cloud Security Guidance v4',
  'incident-response-basics':       'NIST SP 800-61 Rev 2 (Computer Security Incident Handling Guide) + SANS Incident Handler\'s Handbook',
  'soc-analyst-fundamentals':       'CompTIA CySA+ CS0-003 Exam Objectives + MITRE ATT&CK Framework — attack.mitre.org',
  'cryptography-basics':            'NIST FIPS Standards + Applied Cryptography (Schneier) + CompTIA Security+ cryptography domain',

  // LOGIC
  'razonamiento-matematico-basico': 'Cursos de Razonamiento Lógico-Matemático para pruebas psicotécnicas (estilo ICFES, SENA, concursos públicos Colombia)',
  'razonamiento-verbal-basico':     'Pruebas de aptitud verbal estilo ICFES Saber 11 / Saber Pro Colombia',
  'aptitud-numerica-avanzada':      'Psicotécnicos para oposiciones (nivel intermedio) + pruebas estilo GMAT Quant',
  'pensamiento-critico':            'The Foundation for Critical Thinking — criticalthinking.org + Watson-Glaser Critical Thinking Appraisal',
  'icfes-saber-pro-basico':         'ICFES Saber Pro — Guía de Orientación Competencias Genéricas 2023 — icfes.gov.co',

  // ─── ALTO VOLUMEN DE BÚSQUEDA (SEO) — generadas por exam-content-architect ───
  'aws-solutions-architect-associate': 'AWS Certified Solutions Architect – Associate (SAA-C03) Exam Guide — 4 dominios: Design Secure (30%), Design Resilient (26%), Design High-Performing (24%), Design Cost-Optimized (20%) — d1.awsstatic.com/training-and-certification/docs-sa-assoc/AWS-Certified-Solutions-Architect-Associate_Exam-Guide_C03.pdf',
  'comptia-security-plus':          'CompTIA Security+ (SY0-701), única versión vigente desde nov-2023 (SY0-601 retirado jul-2026) — 5 dominios: General Security Concepts (12%), Threats/Vulnerabilities/Mitigations (22%), Security Architecture (18%), Security Operations (28%), Security Program Mgmt & Oversight (20%) — comptia.org/certifications/security',
  'pmp-fundamentos':                'PMI PMP Examination Content Outline (ECO) 2026, vigente desde jul-2026 — 3 dominios: People (33%), Process (41%), Business Environment (26%); ~60% del examen enfocado en agile/híbrido — pmi.org/certifications/project-management-pmp',
  'csm-scrum-master':                'Scrum Alliance Certified ScrumMaster (CSM) — examen de 50 preguntas, 60 min, 74% para aprobar; enfoque en roles, eventos y artefactos de Scrum — scrumalliance.org/get-certified/scrum-master-track/certified-scrummaster',
  'cna-fundamentos':                'NNAAP (National Nurse Aide Assessment Program) Written Exam — 3 áreas: Physical Care Skills (64%), Role of the Nurse Aide (26%), Psychosocial Care Skills (10%) — 70 preguntas (60 evaluadas), 90 min — headmaster.com/nnaap',
  'duolingo-english-test':           'Duolingo English Test (DET) — test adaptativo de 60 min, subscores de literacy/comprehension/conversation/production, escala 10-160 — englishtest.duolingo.com',
};

export const EXAM_CATALOG = [
  // ─── SPORTS / FITNESS ───
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'nsca-cscs-fundamentos', title: 'NSCA CSCS — Especialista en Fuerza y Acondicionamiento', description: 'Examen de práctica para la certificación NSCA CSCS con foco en ciencias del ejercicio, evaluación y diseño del programa.', domain: 'sports', category: 'strength-conditioning', level: 'advanced', tags: ['nsca','cscs','fuerza'], topics: 'Ciencias del ejercicio (bioenergética, anatomía funcional), nutrición deportiva, evaluación de atletas, diseño del programa (periodización, selección de ejercicios), técnica de levantamientos olímpicos, administración y aspectos legales' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'crossfit-level1-basics', title: 'CrossFit Level 1 — Fundamentos', description: 'Preguntas sobre los nueve movimientos fundamentales, metodología CrossFit y seguridad en el entrenamiento funcional.', domain: 'sports', category: 'functional-fitness', level: 'beginner', tags: ['crossfit','wod','functional'], topics: 'Nueve movimientos fundamentales (air squat, front squat, overhead squat, shoulder press, push press, push jerk, deadlift, sumo deadlift high pull, medicine ball clean), metodología CrossFit, escalado, programación WOD, nutrición CrossFit, prevención de lesiones' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'pilates-instructor-basico', title: 'Pilates Instructor Básico', description: 'Examen sobre principios del método Pilates, repertorio mat y enseñanza segura.', domain: 'sports', category: 'mind-body', level: 'beginner', tags: ['pilates','mat','core'], topics: 'Seis principios del método Pilates (concentración, control, centrado, fluidez, precisión, respiración), anatomía aplicada (powerhouse), repertorio mat clásico, modificaciones y contraindicaciones, enseñanza con cueing efectivo' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'yoga-ryt200-fundamentos', title: 'Yoga RYT-200 — Fundamentos', description: 'Examen sobre asanas, pranayama, anatomía del yoga y filosofía básica para instructores RYT-200.', domain: 'sports', category: 'mind-body', level: 'beginner', tags: ['yoga','ryt200','asana'], topics: 'Asanas fundamentales (pie, sentadas, supinas, invertidas), anatomía aplicada al yoga, pranayama básico, ocho ramas del yoga (Yoga Sutras de Patañjali), secuenciación de clases, ajustes y modificaciones' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'entrenamiento-fuerza-resistencia', title: 'Entrenamiento de Fuerza y Resistencia', description: 'Preguntas integrales sobre métodos de entrenamiento, periodización y adaptaciones fisiológicas.', domain: 'sports', category: 'training-theory', level: 'intermediate', tags: ['fuerza','resistencia','periodizacion'], topics: 'Métodos de entrenamiento de fuerza (lineal, ondulada, en bloques), adaptaciones neurales y musculares, métodos de resistencia (continuo, intervalado, fartlek, HIIT), supercompensación, fatiga y recuperación, transferencia al deporte' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'nutricion-deportiva-basica', title: 'Nutrición Deportiva Básica', description: 'Examen sobre macronutrientes, hidratación y suplementación para deportistas amateurs.', domain: 'sports', category: 'nutrition', level: 'beginner', tags: ['nutricion','deporte','suplementos'], topics: 'Requerimientos energéticos del deportista, distribución de macronutrientes según deporte, timing nutricional pre/intra/post entrenamiento, hidratación y electrolitos, suplementos basados en evidencia (creatina, cafeína, proteína, beta-alanina)' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'primeros-auxilios-deportivos', title: 'Primeros Auxilios Deportivos', description: 'Atención inmediata a lesiones deportivas, RCP básico y prevención.', domain: 'sports', category: 'first-aid', level: 'beginner', tags: ['primeros-auxilios','lesiones'], topics: 'Evaluación primaria del deportista lesionado (ABCDE), manejo de esguinces, fracturas y luxaciones (RICE/POLICE), conmoción cerebral, golpe de calor, lesiones musculares agudas, RCP básico y uso del DEA' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'futbol-entrenador-basico', title: 'Fútbol — Entrenador Básico', description: 'Fundamentos tácticos, técnicos y de planificación para entrenadores de fútbol base.', domain: 'sports', category: 'team-sports', level: 'beginner', tags: ['futbol','entrenador','tactica'], topics: 'Fundamentos técnicos individuales (control, pase, conducción, remate), principios tácticos ofensivos y defensivos, sistemas de juego (4-4-2, 4-3-3), preparación física específica, metodología de entrenamiento por etapas, reglamento FIFA básico' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'atletismo-fundamentos', title: 'Atletismo — Fundamentos', description: 'Técnicas de carreras, saltos y lanzamientos, más reglamento básico de atletismo.', domain: 'sports', category: 'individual-sports', level: 'beginner', tags: ['atletismo','carreras','saltos'], topics: 'Técnica de carreras (velocidad, vallas, fondo), técnica de saltos (largo, alto, triple, pértiga), técnica de lanzamientos (peso, disco, jabalina, martillo), reglamento World Athletics, planificación anual del atleta' },
  { batch: 'sports', exportName: 'SPORTS_SETS', slug: 'natacion-instructor', title: 'Natación — Instructor Básico', description: 'Enseñanza de los cuatro estilos, salvamento acuático y didáctica de la natación.', domain: 'sports', category: 'water-sports', level: 'beginner', tags: ['natacion','instructor'], topics: 'Técnica de los cuatro estilos (crol, espalda, braza, mariposa), didáctica progresiva por niveles, salvamento acuático básico, prevención de ahogamiento, planificación de sesiones, reglamento FINA' },

  // ─── HEALTH EXTENDED ───
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'bls-basic-life-support', title: 'BLS — Soporte Vital Básico (AHA)', description: 'Examen estilo AHA BLS Provider sobre RCP, DEA y atención de OVACE.', domain: 'health', category: 'emergency', level: 'beginner', tags: ['bls','rcp','dea'], topics: 'Cadena de supervivencia adulto y pediátrica, RCP de alta calidad (compresiones, ventilaciones, ratio), uso del DEA, OVACE (obstrucción de vía aérea), RCP en equipo, situaciones especiales (embarazo, ahogamiento)' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'acls-advanced-cardiac', title: 'ACLS — Soporte Vital Avanzado', description: 'Algoritmos AHA de paro cardiaco, bradicardia, taquicardia y SCA.', domain: 'health', category: 'emergency', level: 'advanced', tags: ['acls','algoritmos','aha'], topics: 'Algoritmo de paro cardiaco (FV/TV sin pulso, AESP/asistolia), bradicardia con pulso, taquicardia con pulso, SCA, ACV, fármacos ACLS (adrenalina, amiodarona, atropina), dinámica de equipo de alto rendimiento' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'farmacologia-basica', title: 'Farmacología Básica', description: 'Principios de farmacocinética, farmacodinamia y grupos terapéuticos clave.', domain: 'health', category: 'pharmacology', level: 'intermediate', tags: ['farmacologia','medicamentos'], topics: 'Farmacocinética (ADME), farmacodinamia (receptores, agonistas, antagonistas), antibióticos por familias, antihipertensivos, analgésicos (AINEs, opioides), psicofármacos básicos, interacciones medicamentosas frecuentes' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'enfermeria-clinica-basica', title: 'Enfermería Clínica Básica', description: 'Cuidados básicos, signos vitales, administración de medicamentos y bioseguridad.', domain: 'health', category: 'nursing', level: 'beginner', tags: ['enfermeria','clinica'], topics: 'Toma e interpretación de signos vitales, vías de administración de medicamentos (5 correctos), aislamientos y precauciones estándar, manejo de heridas y úlceras por presión, balance hídrico, registros clínicos' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'nclex-rn-fundamentos', title: 'NCLEX-RN — Fundamentos', description: 'Preguntas estilo NCLEX-RN sobre cuidado seguro, fisiopatología y juicio clínico.', domain: 'health', category: 'nursing', level: 'advanced', tags: ['nclex','rn','enfermeria'], topics: 'Cuidado seguro y efectivo, promoción de la salud, integridad psicosocial, integridad fisiológica (cuidados básicos, reducción de riesgo, adaptación fisiológica, terapias farmacológicas y parenterales), priorización y delegación' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'nutricion-clinica-basica', title: 'Nutrición Clínica Básica', description: 'Valoración nutricional, dietoterapia y soporte nutricional especializado.', domain: 'health', category: 'nutrition', level: 'intermediate', tags: ['nutricion','clinica','dietoterapia'], topics: 'Valoración nutricional (antropometría, bioquímica, dietética), dietoterapia en diabetes, hipertensión, ERC, hepatopatía, soporte nutricional enteral y parenteral, requerimientos en cirugía y trauma, malnutrición hospitalaria' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'salud-mental-basica', title: 'Salud Mental Básica', description: 'Trastornos comunes, primeros auxilios psicológicos y promoción de salud mental.', domain: 'health', category: 'mental-health', level: 'beginner', tags: ['salud-mental','primeros-auxilios-psicologicos'], topics: 'Trastornos depresivos y de ansiedad (síntomas DSM-5/CIE-11), trastornos por uso de sustancias, riesgo suicida y evaluación, primeros auxilios psicológicos, derivación a especialista, mitos y estigma' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'ecg-interpretacion-basica', title: 'ECG — Interpretación Básica', description: 'Lectura sistemática del ECG de 12 derivaciones y reconocimiento de arritmias frecuentes.', domain: 'health', category: 'cardiology', level: 'intermediate', tags: ['ecg','arritmias','cardiologia'], topics: 'Sistema de conducción cardiaca, lectura sistemática del ECG (frecuencia, ritmo, eje, intervalos), arritmias supraventriculares (FA, flutter, TSV), arritmias ventriculares, bloqueos AV, signos de isquemia (ST/T)' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'pediatria-basica', title: 'Pediatría Básica', description: 'Crecimiento, desarrollo, vacunación y patologías pediátricas frecuentes.', domain: 'health', category: 'pediatrics', level: 'intermediate', tags: ['pediatria','niños'], topics: 'Crecimiento y desarrollo por etapas, esquema de vacunación, lactancia y alimentación complementaria, infecciones respiratorias agudas, enfermedad diarreica aguda, deshidratación y rehidratación oral, fiebre en pediatría' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'primeros-auxilios-avanzados', title: 'Primeros Auxilios Avanzados', description: 'Trauma, hemorragias, quemaduras y emergencias médicas más allá de lo básico.', domain: 'health', category: 'emergency', level: 'intermediate', tags: ['trauma','primeros-auxilios'], topics: 'Evaluación primaria y secundaria (XABCDE), control de hemorragias (torniquetes, vendajes hemostáticos), inmovilización de fracturas, quemaduras (regla de los 9, manejo inicial), emergencias médicas (hipoglucemia, crisis convulsiva, anafilaxia, IAM)' },

  // ─── BUSINESS / MARKETING ───
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'google-analytics-4-certified', title: 'Google Analytics 4 Certified', description: 'Examen de la certificación oficial GA4 sobre eventos, audiencias e informes.', domain: 'business', category: 'digital-analytics', level: 'intermediate', tags: ['ga4','analytics','google'], topics: 'Modelo de datos GA4 basado en eventos, configuración de propiedades y flujos de datos, eventos automáticos vs personalizados, conversiones, audiencias, exploraciones, informes estándar, integración con Google Ads y BigQuery' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'google-ads-search-certified', title: 'Google Ads Search Certified', description: 'Certificación oficial Google Ads — Búsqueda: pujas, calidad del anuncio, palabras clave.', domain: 'business', category: 'paid-media', level: 'intermediate', tags: ['google-ads','sem','search'], topics: 'Estructura de cuentas Google Ads, tipos de concordancia de palabras clave, pujas inteligentes (tCPA, tROAS, Maximizar conversiones), calidad del anuncio y Quality Score, RSA (Anuncios Adaptables de Búsqueda), extensiones, informes y atribución' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'meta-blueprint-certified', title: 'Meta Blueprint — Digital Marketing Associate', description: 'Examen Meta Blueprint sobre Facebook e Instagram Ads, Pixel y CAPI.', domain: 'business', category: 'paid-media', level: 'intermediate', tags: ['meta','facebook','instagram'], topics: 'Estructura del Administrador de Anuncios Meta, objetivos de campaña, segmentación y públicos personalizados/similares, Meta Pixel y Conversions API, Advantage+ Shopping Campaigns, creatividades por placement, medición y optimización' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'hubspot-inbound-marketing', title: 'HubSpot Inbound Marketing', description: 'Metodología inbound, buyer personas, contenido y nurturing.', domain: 'business', category: 'inbound-marketing', level: 'beginner', tags: ['hubspot','inbound'], topics: 'Metodología inbound (atraer, interactuar, deleitar), flywheel vs funnel, buyer personas y journey, estrategia de contenido, SEO on-page, lead nurturing y email marketing, smarketing (alineación marketing-ventas)' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'salesforce-admin-adm201', title: 'Salesforce Administrator (ADM-201)', description: 'Examen estilo Salesforce Certified Administrator.', domain: 'business', category: 'crm', level: 'intermediate', tags: ['salesforce','admin','crm'], topics: 'Configuración de la organización, gestión de usuarios y seguridad (perfiles, permission sets, OWD), modelo de datos (objetos, campos, relaciones), automatización (Flow, validation rules), informes y dashboards, gestión de datos (import wizard, Data Loader)' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'digital-marketing-fundamentals', title: 'Marketing Digital — Fundamentos', description: 'Visión integral del marketing digital: SEO, SEM, redes, email y analítica.', domain: 'business', category: 'digital-marketing', level: 'beginner', tags: ['marketing-digital','seo','sem'], topics: 'Ecosistema digital (canales pagos, propios, ganados), SEO básico (on-page, off-page, técnico), SEM y modelos de puja, social media marketing, email marketing y automatización, embudo de conversión, KPIs y atribución' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'seo-fundamentals', title: 'SEO — Fundamentos', description: 'Optimización on-page, off-page, técnica y Core Web Vitals.', domain: 'business', category: 'seo', level: 'intermediate', tags: ['seo','google','indexacion'], topics: 'Cómo funcionan los buscadores (crawl, index, rank), SEO on-page (titles, meta, headings, contenido), SEO técnico (sitemap, robots, canonical, structured data), backlinks y autoridad, Core Web Vitals, SEO local, herramientas (GSC, GA4, Screaming Frog)' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'email-marketing-fundamentals', title: 'Email Marketing — Fundamentos', description: 'Listas, segmentación, deliverability y automatización de email.', domain: 'business', category: 'email-marketing', level: 'beginner', tags: ['email','newsletter','automatizacion'], topics: 'Construcción y segmentación de listas, double opt-in y consentimiento (GDPR/LGPD), deliverability (SPF, DKIM, DMARC), copywriting de subject lines, A/B testing, automatización (welcome, abandono, reactivación), KPIs (open rate, CTR, conversión)' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'product-management-basics', title: 'Product Management — Fundamentos', description: 'Discovery, roadmap, métricas y frameworks de producto.', domain: 'business', category: 'product', level: 'intermediate', tags: ['product','pm','agile'], topics: 'Rol del Product Manager, discovery vs delivery, frameworks (RICE, MoSCoW, Kano, Jobs-to-be-Done), creación de roadmaps y OKRs, métricas de producto (AARRR, North Star), MVP y experimentación, gestión de stakeholders' },
  { batch: 'business', exportName: 'BUSINESS_SETS', slug: 'data-analytics-google-certificate', title: 'Google Data Analytics Certificate', description: 'Examen final estilo Google Data Analytics Professional Certificate (Coursera).', domain: 'business', category: 'data-analytics', level: 'intermediate', tags: ['data','analytics','google'], topics: 'Ciclo de vida del análisis de datos (preguntar, preparar, procesar, analizar, compartir, actuar), tipos de datos y bases de datos, SQL básico, limpieza de datos, visualización (Tableau, Looker Studio), R básico, ética y privacidad de datos' },

  // ─── CLOUD EXTENDED ───
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'aws-developer-associate', title: 'AWS Developer Associate (DVA-C02)', description: 'Examen estilo AWS Certified Developer — Associate.', domain: 'it', category: 'cloud-aws', level: 'advanced', tags: ['aws','developer','dva'], topics: 'Desarrollo con AWS SDKs, Lambda y serverless, API Gateway, DynamoDB (modelo de datos, índices, capacidad), S3 (storage classes, encriptación, presigned URLs), IAM (roles, políticas), CI/CD con CodePipeline/CodeBuild/CodeDeploy, observabilidad (CloudWatch, X-Ray)' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'aws-sysops-administrator', title: 'AWS SysOps Administrator (SOA-C02)', description: 'Operaciones, monitoreo y automatización en AWS.', domain: 'it', category: 'cloud-aws', level: 'advanced', tags: ['aws','sysops','operations'], topics: 'Monitoreo y reporting (CloudWatch, EventBridge, CloudTrail), reliability y BCP (backups, multi-AZ, multi-región), deployment y aprovisionamiento (CloudFormation, Systems Manager), seguridad operativa, networking (VPC, Route 53, Direct Connect), gestión de costes' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'azure-administrator-az104', title: 'Microsoft Azure Administrator (AZ-104)', description: 'Examen estilo AZ-104: identidades, gobernanza, redes y storage en Azure.', domain: 'it', category: 'cloud-azure', level: 'advanced', tags: ['azure','az-104','administrator'], topics: 'Identidades Azure AD/Entra ID, gobernanza (RBAC, Policy, Blueprints), redes virtuales (VNet, NSG, peering, VPN, ExpressRoute), almacenamiento (Blob, Files, niveles de acceso), cómputo (VMs, escalado), monitoreo (Azure Monitor, Log Analytics)' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'gcp-cloud-digital-leader', title: 'Google Cloud Digital Leader', description: 'Certificación de entrada GCP enfocada en valor de negocio del cloud.', domain: 'it', category: 'cloud-gcp', level: 'beginner', tags: ['gcp','google-cloud','cdl'], topics: 'Transformación digital con Google Cloud, infraestructura y modernización de aplicaciones, datos y machine learning con GCP (BigQuery, Vertex AI), seguridad y compliance, soporte y operaciones, principios de pricing' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'terraform-associate', title: 'HashiCorp Terraform Associate', description: 'Infraestructura como código con Terraform.', domain: 'it', category: 'iac', level: 'intermediate', tags: ['terraform','iac','hashicorp'], topics: 'Conceptos de IaC, workflow de Terraform (init, plan, apply, destroy), state (local, remote, locking), módulos y composición, providers y resources, variables y outputs, Terraform Cloud, debugging y troubleshooting' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'azure-developer-az204', title: 'Azure Developer Associate (AZ-204)', description: 'Desarrollo de soluciones cloud-native en Azure.', domain: 'it', category: 'cloud-azure', level: 'advanced', tags: ['azure','az-204','developer'], topics: 'Compute solutions (App Service, Functions, Container Apps), storage (Blob, Cosmos DB), seguridad (Managed Identities, Key Vault), monitoreo (Application Insights), conexión a servicios de terceros (Service Bus, Event Grid, Event Hub), API Management' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'comptia-network-plus', title: 'CompTIA Network+ (N10-008)', description: 'Fundamentos de redes para certificación CompTIA Network+.', domain: 'it', category: 'networking', level: 'intermediate', tags: ['comptia','network','redes'], topics: 'Fundamentos de redes (modelo OSI, TCP/IP), implementación de redes (cableado, dispositivos, IP addressing), operaciones de red (monitoreo, BCP), seguridad de red (autenticación, ataques, mitigación), troubleshooting de red' },
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'rest-api-design', title: 'REST API Design — Mejores Prácticas', description: 'Diseño de APIs RESTful: recursos, verbos, versionado y seguridad.', domain: 'it', category: 'api-design', level: 'intermediate', tags: ['api','rest','http'], topics: 'Principios REST (recursos, representaciones, stateless), uso correcto de verbos HTTP y códigos de estado, naming conventions, versionado de APIs, paginación, filtrado y ordenamiento, autenticación (OAuth 2.0, JWT), documentación (OpenAPI/Swagger), idempotencia' },

  // ─── DEVOPS / PROGRAMMING ───
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'python-pcep-beginner', title: 'Python PCEP — Certified Entry Programmer', description: 'Examen estilo PCEP-30-02 sobre fundamentos de Python.', domain: 'it', category: 'programming', level: 'beginner', tags: ['python','pcep','programming'], topics: 'Conceptos básicos de computación, tipos de datos en Python (int, float, str, bool), operadores y expresiones, control de flujo (if, while, for), funciones, listas, tuplas, diccionarios, manejo básico de excepciones' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'python-pcap-intermediate', title: 'Python PCAP — Certified Associate Programmer', description: 'Examen estilo PCAP-31-03 sobre Python intermedio.', domain: 'it', category: 'programming', level: 'intermediate', tags: ['python','pcap','oop'], topics: 'Módulos y paquetes, manejo avanzado de excepciones, programación orientada a objetos (clases, herencia, polimorfismo), expresiones generadoras, decoradores, manejo de archivos, biblioteca estándar (os, datetime, math)' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'javascript-fundamentals', title: 'JavaScript — Fundamentos', description: 'Examen sobre JavaScript moderno (ES6+) y conceptos clave del lenguaje.', domain: 'it', category: 'programming', level: 'beginner', tags: ['javascript','es6','frontend'], topics: 'Tipos primitivos y objetos, var/let/const y scope, funciones (declaración, expresión, arrow), closures, this y binding, prototipos y clases ES6, promesas y async/await, módulos ES6, manipulación básica del DOM' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'java-foundations', title: 'Java Foundations', description: 'Examen estilo Java SE Foundations sobre sintaxis y POO.', domain: 'it', category: 'programming', level: 'beginner', tags: ['java','jvm','oop'], topics: 'Sintaxis Java, tipos primitivos y wrappers, control de flujo, arrays, programación orientada a objetos (clases, herencia, interfaces), excepciones (checked vs unchecked), Collections Framework básico, JVM y classpath' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'mongodb-developer-basics', title: 'MongoDB Developer — Fundamentos', description: 'Modelado, consultas y operaciones básicas en MongoDB.', domain: 'it', category: 'database', level: 'intermediate', tags: ['mongodb','nosql','database'], topics: 'Modelo de datos documental, CRUD operations, query operators ($eq, $gt, $in, $regex), aggregation pipeline básico ($match, $group, $project, $lookup), índices y rendimiento, replica sets, sharding básico' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'postgresql-fundamentals', title: 'PostgreSQL — Fundamentos', description: 'SQL relacional, tipos de datos PostgreSQL y administración básica.', domain: 'it', category: 'database', level: 'intermediate', tags: ['postgresql','sql','rdbms'], topics: 'SQL DDL/DML/DCL, tipos de datos PostgreSQL (incluyendo JSONB, arrays), índices (B-tree, GIN, GiST), JOINs y subconsultas, transacciones y niveles de aislamiento, vistas y CTEs, EXPLAIN ANALYZE básico, roles y permisos' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'devops-fundamentals', title: 'DevOps — Fundamentos', description: 'Cultura DevOps, CI/CD, IaC y observabilidad.', domain: 'it', category: 'devops', level: 'beginner', tags: ['devops','cicd','culture'], topics: 'Cultura DevOps (CALMS), DORA metrics, CI/CD (build, test, deploy), branching strategies (Trunk Based, GitFlow), Infrastructure as Code, contenedores y orquestación, observabilidad (logs, métricas, traces), SRE básico' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'ansible-fundamentals', title: 'Ansible — Fundamentos', description: 'Automatización con Ansible: playbooks, roles y inventarios.', domain: 'it', category: 'devops', level: 'intermediate', tags: ['ansible','automation','iac'], topics: 'Arquitectura agentless de Ansible, inventarios (estáticos y dinámicos), playbooks YAML, módulos comunes (file, copy, template, service, package), variables y facts, handlers, roles y Ansible Galaxy, Ansible Vault' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'jenkins-fundamentals', title: 'Jenkins — Fundamentos', description: 'CI/CD con Jenkins: pipelines, agentes y plugins.', domain: 'it', category: 'devops', level: 'intermediate', tags: ['jenkins','cicd','pipeline'], topics: 'Arquitectura controller/agent, configuración de jobs (Freestyle vs Pipeline), Jenkinsfile (declarative vs scripted), agents y nodos, gestión de credentials, plugins esenciales (Git, Docker, SonarQube), shared libraries, Blue Ocean' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'redis-fundamentals', title: 'Redis — Fundamentos', description: 'Estructuras de datos, persistencia y patrones de uso de Redis.', domain: 'it', category: 'database', level: 'intermediate', tags: ['redis','cache','nosql'], topics: 'Estructuras de datos Redis (strings, hashes, lists, sets, sorted sets, streams), comandos básicos, persistencia (RDB, AOF), pub/sub, expiración y TTL, casos de uso (cache, session store, rate limiting, leaderboards), Redis Cluster' },
  { batch: 'devops-programming', exportName: 'DEVOPS_PROGRAMMING_SETS', slug: 'git-advanced', title: 'Git Avanzado', description: 'Rebase, cherry-pick, reflog, hooks y workflows complejos.', domain: 'it', category: 'devops', level: 'advanced', tags: ['git','version-control','advanced'], topics: 'Rebase interactivo y squash, cherry-pick, reflog y recuperación, stash avanzado, hooks (client/server-side), submódulos y subtrees, bisect para debugging, workflows (Trunk Based, Git Flow, GitHub Flow), resolución avanzada de conflictos' },

  // ─── ENGLISH EXTENDED ───
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'english-b2-upper-intermediate', title: 'English B2 — Upper Intermediate', description: 'Examen nivel B2 (CEFR) sobre gramática, vocabulario y comprensión.', domain: 'english', category: 'cefr', level: 'intermediate', tags: ['english','b2','cefr'], topics: 'Tiempos verbales avanzados (perfect continuous, mixed conditionals), reported speech, passive voice, modal verbs of deduction, phrasal verbs comunes, vocabulario académico y profesional, comprensión de textos B2', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'english-c1-advanced', title: 'English C1 — Advanced', description: 'Nivel C1 (CEFR): gramática avanzada, idioms y comprensión académica.', domain: 'english', category: 'cefr', level: 'advanced', tags: ['english','c1','cae'], topics: 'Inversión enfática, cleft sentences, advanced conditionals, hedging language, idioms y expresiones formales, collocations, lectura crítica de textos académicos, vocabulario C1', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'ielts-academic-reading', title: 'IELTS Academic — Reading', description: 'Estrategias y práctica de los tres pasajes IELTS Academic Reading.', domain: 'english', category: 'ielts', level: 'advanced', tags: ['ielts','reading','academic'], topics: 'Tipos de preguntas IELTS (matching headings, true/false/not given, sentence completion, multiple choice), skimming y scanning, manejo del tiempo, vocabulario académico, paráfrasis, identificación de la idea principal', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'ielts-academic-writing', title: 'IELTS Academic — Writing', description: 'Task 1 (gráficos) y Task 2 (ensayo) del IELTS Academic Writing.', domain: 'english', category: 'ielts', level: 'advanced', tags: ['ielts','writing','academic'], topics: 'Task 1: descripción de gráficos, tablas y procesos; Task 2: tipos de ensayos (opinion, discussion, problem-solution, advantages-disadvantages); cohesion y coherence; lexical resource; grammatical range and accuracy; criterios de banda', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'toefl-ibt-fundamentals', title: 'TOEFL iBT — Fundamentos', description: 'Estructura y estrategias de las cuatro secciones del TOEFL iBT.', domain: 'english', category: 'toefl', level: 'advanced', tags: ['toefl','ibt'], topics: 'Reading (academic passages, integrated questions), Listening (lectures, conversations), Speaking (independent, integrated tasks), Writing (integrated, academic discussion), gestión del tiempo, vocabulario académico TOEFL', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'toeic-listening-reading', title: 'TOEIC Listening & Reading', description: 'Examen TOEIC L&R orientado a inglés de negocios.', domain: 'english', category: 'toeic', level: 'intermediate', tags: ['toeic','business-english'], topics: 'Listening: photographs, question-response, conversations, talks; Reading: incomplete sentences, text completion, single y double passages; vocabulario de negocios; estrategias por tipo de pregunta', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'business-english-b2', title: 'Business English — B2', description: 'Inglés de negocios nivel B2: emails, reuniones, negociaciones.', domain: 'english', category: 'business-english', level: 'intermediate', tags: ['business','english','b2'], topics: 'Email writing (formal/informal, requests, complaints), meetings (chairing, participating, agreeing/disagreeing), presentations (signposting, transitions), negotiations, telephone English, vocabulario corporativo', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'english-grammar-advanced', title: 'English Grammar — Advanced', description: 'Estructuras gramaticales avanzadas del inglés.', domain: 'english', category: 'grammar', level: 'advanced', tags: ['grammar','english','advanced'], topics: 'Tiempos verbales perfectos y continuos, modales perfectos, mixed conditionals, inversion, cleft sentences, subjuntivo (mandative), participles y participle clauses, gerunds vs infinitives con cambio de significado', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'academic-vocabulary-advanced', title: 'Academic Vocabulary — Advanced', description: 'Vocabulario académico (AWL) y collocations para C1/C2.', domain: 'english', category: 'vocabulary', level: 'advanced', tags: ['vocabulary','awl','academic'], topics: 'Academic Word List (AWL), collocations académicas, transition words y discourse markers, hedging language, prefijos y sufijos académicos, sinónimos formales vs informales, palabras frecuentemente confundidas', topicsLanguage: 'mixed' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'english-pronunciation-phonetics', title: 'English Pronunciation & Phonetics', description: 'IPA, sonidos del inglés, stress y entonación.', domain: 'english', category: 'phonetics', level: 'intermediate', tags: ['pronunciation','phonetics','ipa'], topics: 'Alfabeto fonético internacional (IPA), sonidos vocálicos (monoftongos, diptongos), sonidos consonánticos (oclusivas, fricativas, africadas), word stress y patrones, sentence stress y rhythm, entonación (rising, falling), connected speech (linking, elision, assimilation)', topicsLanguage: 'mixed' },

  // ─── AGILE EXTENDED ───
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'scrum-product-owner-pspo', title: 'Scrum.org PSPO I — Product Owner', description: 'Examen estilo PSPO I: rol del Product Owner, valor y backlog.', domain: 'agile', category: 'scrum', level: 'intermediate', tags: ['scrum','pspo','product-owner'], topics: 'Marco Scrum y rol del Product Owner, Producto y meta de producto, Product Backlog y refinement, gestión de stakeholders, valor entregado y métricas, Sprint Planning desde la perspectiva del PO, Sprint Review' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'safe-scrum-master', title: 'SAFe Scrum Master (SSM)', description: 'Scrum Master en SAFe: ART, PI Planning y servant leadership.', domain: 'agile', category: 'safe', level: 'advanced', tags: ['safe','sm','scaled-agile'], topics: 'Scaled Agile Framework, rol del SM en el Agile Release Train (ART), PI Planning y eventos, facilitación de iteraciones, dependencias entre equipos, métricas SAFe, coaching y servant leadership, Lean-Agile mindset' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'kanban-management-professional', title: 'Kanban Management Professional (KMP)', description: 'Método Kanban: principios, prácticas y métricas de flujo.', domain: 'agile', category: 'kanban', level: 'intermediate', tags: ['kanban','flow','lean'], topics: 'Principios y prácticas del Método Kanban, visualización del flujo, límites WIP, gestión del flujo, políticas explícitas, ciclos de feedback, mejora colaborativa, métricas (lead time, cycle time, throughput, CFD), Kanban Maturity Model' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'prince2-foundation', title: 'PRINCE2 Foundation', description: 'Examen Foundation de PRINCE2: principios, temas y procesos.', domain: 'agile', category: 'project-management', level: 'intermediate', tags: ['prince2','foundation','pm'], topics: '7 principios PRINCE2, 7 temas (Business Case, Organization, Quality, Plans, Risk, Change, Progress), 7 procesos (SU, IP, DP, CS, MP, SB, CP), tailoring, roles y responsabilidades, productos de gestión' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'lean-six-sigma-yellow-belt', title: 'Lean Six Sigma Yellow Belt', description: 'Examen Yellow Belt de Lean Six Sigma.', domain: 'agile', category: 'lean-six-sigma', level: 'beginner', tags: ['six-sigma','yellow-belt','lean'], topics: 'Historia y filosofía Lean Six Sigma, los 8 desperdicios (DOWNTIME), DMAIC overview, voz del cliente y CTQ, herramientas básicas (5S, mapeo de procesos, diagrama de Ishikawa, 5 porqués), métricas básicas (DPMO, sigma level)' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'pmi-capm-fundamentals', title: 'PMI CAPM — Fundamentos', description: 'Certified Associate in Project Management (CAPM) del PMI.', domain: 'agile', category: 'project-management', level: 'beginner', tags: ['capm','pmi','pmbok'], topics: 'PMBOK Guide y Standards Plus, dominios de performance (Stakeholders, Team, Development Approach, Planning, Project Work, Delivery, Measurement, Uncertainty), modelos predictivos vs adaptativos, business case, ética del PMI' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'design-thinking-fundamentals', title: 'Design Thinking — Fundamentos', description: 'Proceso, mindset y herramientas de Design Thinking.', domain: 'agile', category: 'innovation', level: 'beginner', tags: ['design-thinking','innovation','ux'], topics: '5 etapas del Design Thinking (Empathize, Define, Ideate, Prototype, Test), mindset (human-centered, iterativo, colaborativo), herramientas de empatía (entrevistas, mapa de empatía, journey map), técnicas de ideación (brainstorming, Crazy 8s, SCAMPER), prototipado rápido, testing con usuarios' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'agile-coaching-basics', title: 'Agile Coaching — Fundamentos', description: 'Competencias del Agile Coach: facilitación, coaching y mentoring.', domain: 'agile', category: 'coaching', level: 'intermediate', tags: ['coaching','agile','facilitation'], topics: 'Diferencias entre coaching, mentoring, facilitating y consulting, modelos (GROW, ICAgile competency framework), powerful questions, escucha activa, facilitación de retrospectivas, manejo de conflictos, coaching de equipos vs individual, ética del coaching' },

  // ─── SECURITY EXTENDED ───
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'certified-ethical-hacker-basics', title: 'Certified Ethical Hacker (CEH) — Fundamentos', description: 'Conceptos clave del examen CEH v12.', domain: 'security', category: 'ethical-hacking', level: 'advanced', tags: ['ceh','pentesting','hacking'], topics: 'Fases del hacking ético (reconocimiento, scanning, gaining access, maintaining access, covering tracks), footprinting, enumeración, vulnerabilidades de sistema, malware, sniffing, ingeniería social, denegación de servicio, hijacking de sesión' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'cissp-domain-fundamentals', title: 'CISSP — Fundamentos por Dominio', description: 'Resumen estilo CISSP: 8 dominios CBK de (ISC)².', domain: 'security', category: 'security-management', level: 'advanced', tags: ['cissp','isc2','infosec'], topics: 'Domain 1: Security and Risk Management, Domain 2: Asset Security, Domain 3: Security Architecture and Engineering, Domain 4: Communication and Network Security, Domain 5: IAM, Domain 6: Security Assessment and Testing, Domain 7: Security Operations, Domain 8: Software Development Security' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'penetration-testing-basics', title: 'Penetration Testing — Fundamentos', description: 'Metodología, herramientas y reporting de pentesting.', domain: 'security', category: 'pentesting', level: 'intermediate', tags: ['pentesting','red-team','offensive'], topics: 'Metodologías (PTES, OSSTMM, OWASP Testing Guide), tipos de pentest (black/grey/white box), reconocimiento (OSINT, nmap), explotación (Metasploit), post-explotación, escalación de privilegios, reporting profesional, marco legal y reglas de engagement' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'network-security-fundamentals', title: 'Network Security — Fundamentos', description: 'Seguridad de redes: firewalls, IDS/IPS, VPN y segmentación.', domain: 'security', category: 'network-security', level: 'intermediate', tags: ['network','firewall','ids'], topics: 'Modelo de defensa en profundidad, firewalls (stateful, NGFW), IDS/IPS, VPNs (IPSec, SSL/TLS), segmentación de red y VLANs, Zero Trust Architecture, ataques de red comunes (MITM, ARP spoofing, DDoS), monitoreo y SIEM' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'cloud-security-fundamentals', title: 'Cloud Security — Fundamentos', description: 'Seguridad en cloud: shared responsibility, IAM y compliance.', domain: 'security', category: 'cloud-security', level: 'intermediate', tags: ['cloud','security','aws','azure'], topics: 'Modelo de responsabilidad compartida, IAM en cloud (least privilege, MFA), encriptación at-rest e in-transit, gestión de secretos (KMS, Key Vault, Secrets Manager), seguridad de containers y Kubernetes, compliance (PCI-DSS, HIPAA, GDPR), CSPM y CWPP' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'incident-response-basics', title: 'Incident Response — Fundamentos', description: 'Manejo de incidentes según NIST SP 800-61.', domain: 'security', category: 'incident-response', level: 'intermediate', tags: ['incident-response','dfir','nist'], topics: 'Ciclo de vida del IR según NIST (Preparation, Detection & Analysis, Containment Eradication & Recovery, Post-Incident), CSIRT y roles, playbooks de IR, evidencia digital y chain of custody, comunicación durante un incidente, lessons learned' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'soc-analyst-fundamentals', title: 'SOC Analyst — Fundamentos', description: 'Operaciones de un SOC: monitoreo, triage y SIEM.', domain: 'security', category: 'soc', level: 'beginner', tags: ['soc','siem','blue-team'], topics: 'Estructura de un SOC (L1, L2, L3), herramientas (SIEM, SOAR, EDR, XDR), análisis de logs, MITRE ATT&CK framework, threat intelligence, triage de alertas, investigación de incidentes, métricas SOC (MTTD, MTTR)' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'cryptography-basics', title: 'Cryptography — Fundamentos', description: 'Criptografía simétrica, asimétrica, hashing y PKI.', domain: 'security', category: 'cryptography', level: 'intermediate', tags: ['crypto','cryptography','pki'], topics: 'Criptografía simétrica (AES, ChaCha20), criptografía asimétrica (RSA, ECC), funciones hash (SHA-256, SHA-3), HMAC, firma digital, PKI y certificados X.509, TLS handshake, gestión de claves, ataques criptográficos comunes' },

  // ─── LOGIC / ICFES ───
  { batch: 'logic-extended', exportName: 'LOGIC_EXTENDED_SETS', slug: 'razonamiento-matematico-basico', title: 'Razonamiento Matemático Básico', description: 'Aritmética, proporcionalidad, álgebra básica y resolución de problemas.', domain: 'logic', category: 'math-reasoning', level: 'beginner', tags: ['matematicas','razonamiento'], topics: 'Operaciones básicas y orden, fracciones y decimales, porcentajes, proporcionalidad directa e inversa, regla de tres, ecuaciones lineales, resolución de problemas verbales, secuencias numéricas' },
  { batch: 'logic-extended', exportName: 'LOGIC_EXTENDED_SETS', slug: 'razonamiento-verbal-basico', title: 'Razonamiento Verbal Básico', description: 'Sinónimos, antónimos, analogías y comprensión lectora.', domain: 'logic', category: 'verbal-reasoning', level: 'beginner', tags: ['verbal','razonamiento','lectura'], topics: 'Sinónimos y antónimos, analogías verbales, comprensión de lectura (idea principal, inferencias), conectores lógicos, reordenamiento de oraciones, vocabulario contextual, identificación de tono e intención' },
  { batch: 'logic-extended', exportName: 'LOGIC_EXTENDED_SETS', slug: 'aptitud-numerica-avanzada', title: 'Aptitud Numérica Avanzada', description: 'Series, problemas de mezclas, edades, trabajo y velocidad.', domain: 'logic', category: 'math-reasoning', level: 'intermediate', tags: ['matematicas','aptitud','psicotecnico'], topics: 'Series numéricas y de letras, problemas de mezclas y aleaciones, problemas de edades, problemas de trabajo (obreros y tiempos), problemas de velocidad-tiempo-distancia, lógica matemática, suficiencia de datos' },
  { batch: 'logic-extended', exportName: 'LOGIC_EXTENDED_SETS', slug: 'pensamiento-critico', title: 'Pensamiento Crítico', description: 'Identificación de argumentos, falacias y evaluación de evidencia.', domain: 'logic', category: 'critical-thinking', level: 'intermediate', tags: ['pensamiento-critico','argumentacion'], topics: 'Estructura de argumentos (premisas y conclusión), tipos de razonamiento (deductivo, inductivo, abductivo), falacias formales e informales (ad hominem, hombre de paja, falsa causa), evaluación de fuentes, sesgos cognitivos, identificación de supuestos' },
  { batch: 'logic-extended', exportName: 'LOGIC_EXTENDED_SETS', slug: 'icfes-saber-pro-basico', title: 'ICFES Saber Pro — Competencias Genéricas', description: 'Examen estilo Saber Pro Colombia: lectura crítica, razonamiento cuantitativo, ciudadanas e inglés.', domain: 'logic', category: 'standardized-test', level: 'intermediate', tags: ['icfes','saber-pro','colombia'], topics: 'Lectura crítica (comprensión, inferencia, evaluación), razonamiento cuantitativo (interpretación de datos, formulación, argumentación), competencias ciudadanas (multiculturalidad, ambiente, convivencia), comunicación escrita, inglés B1', topicsLanguage: 'mixed' },

  // ─── ALTO VOLUMEN DE BÚSQUEDA (SEO) ───
  { batch: 'cloud-extended', exportName: 'CLOUD_EXTENDED_SETS', slug: 'aws-solutions-architect-associate', title: 'AWS Solutions Architect Associate (SAA-C03)', description: 'Examen de práctica alineado a los 4 dominios oficiales de AWS Certified Solutions Architect – Associate: arquitecturas seguras, resilientes, de alto rendimiento y optimizadas en costo.', domain: 'it', category: 'cloud-aws', level: 'advanced', tags: ['aws', 'saa', 'solutions-architect'], topics: 'Diseño de arquitecturas seguras (IAM, VPC, encriptación, controles de acceso), arquitecturas resilientes (multi-AZ, multi-región, backups, desacoplamiento con SQS/SNS), arquitecturas de alto rendimiento (elasticidad, caching, storage por caso de uso), arquitecturas optimizadas en costo (right-sizing, instancias reservadas/spot, storage tiering)' },
  { batch: 'security-extended', exportName: 'SECURITY_EXTENDED_SETS', slug: 'comptia-security-plus', title: 'CompTIA Security+ (SY0-701)', description: 'Examen de práctica alineado a los 5 dominios oficiales de CompTIA Security+ SY0-701: conceptos generales, amenazas, arquitectura, operaciones y gobernanza de seguridad.', domain: 'security', category: 'security-fundamentals', level: 'intermediate', tags: ['comptia', 'security-plus', 'sy0-701'], topics: 'Conceptos generales de seguridad (CIA triad, controles, zero trust), amenazas/vulnerabilidades/mitigaciones (malware, ingeniería social, vectores de ataque), arquitectura de seguridad (cloud, redes, resiliencia), operaciones de seguridad (hardening, gestión de identidades, incident response), gobernanza y gestión de riesgo (políticas, cumplimiento, terceros)' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'pmp-fundamentos', title: 'PMP — Project Management Professional', description: 'Examen de práctica alineado al Examination Content Outline (ECO) 2026 del PMI: dominios People, Process y Business Environment, con enfoque agile/híbrido.', domain: 'agile', category: 'project-management', level: 'advanced', tags: ['pmp', 'pmi', 'project-management'], topics: 'Dominio People (liderazgo de equipo, resolución de conflictos, empoderamiento), dominio Process (planificación, alcance, cronograma, riesgos, calidad, enfoques predictivo/ágil/híbrido), dominio Business Environment (valor de negocio, cumplimiento, cambio organizacional, IA en gestión de proyectos)' },
  { batch: 'agile-extended', exportName: 'AGILE_EXTENDED_SETS', slug: 'csm-scrum-master', title: 'Certified ScrumMaster (CSM) — Scrum Alliance', description: 'Examen de práctica sobre los fundamentos de Scrum evaluados en el CSM de Scrum Alliance: roles, eventos, artefactos y valores ágiles.', domain: 'agile', category: 'scrum', level: 'beginner', tags: ['csm', 'scrum', 'scrum-alliance'], topics: 'Roles de Scrum (Scrum Master, Product Owner, Developers), eventos de Scrum (Sprint, Planning, Daily Scrum, Review, Retrospective), artefactos de Scrum (Product Backlog, Sprint Backlog, Increment) y sus compromisos, valores y principios ágiles (Manifiesto Ágil, valores de Scrum), responsabilidades y servant leadership del Scrum Master' },
  { batch: 'health-extended', exportName: 'HEALTH_EXTENDED_SETS', slug: 'cna-fundamentos', title: 'CNA — Auxiliar de Enfermería (NNAAP)', description: 'Examen de práctica alineado al NNAAP Written Exam para certificación de Certified Nursing Assistant: cuidados físicos, rol del auxiliar y cuidado psicosocial.', domain: 'health', category: 'nursing-assistant', level: 'beginner', tags: ['cna', 'nnaap', 'nurse-aide'], topics: 'Actividades de la vida diaria (higiene, alimentación, movilidad), habilidades básicas de enfermería (signos vitales, control de infecciones, seguridad del paciente, posicionamiento), habilidades restaurativas, rol del auxiliar de enfermería (comunicación, derechos del paciente, ética), cuidado psicosocial (necesidades emocionales, espirituales y culturales)' },
  { batch: 'english-extended', exportName: 'ENGLISH_EXTENDED_SETS', slug: 'duolingo-english-test', title: 'Duolingo English Test (DET) — Preparación', description: 'Preguntas de práctica para las habilidades evaluadas en el Duolingo English Test: reconocimiento de vocabulario, cloze, comprensión lectora y gramática.', domain: 'english', category: 'det', level: 'intermediate', tags: ['duolingo', 'det', 'english-proficiency'], topics: 'Reconocimiento de palabras reales vs. inventadas (yes/no vocabulary task), texto tipo cloze (completar espacios en un párrafo), comprensión de lectura, gramática y estructura de oraciones, vocabulario en contexto', topicsLanguage: 'mixed' },
];
